In [26]:
import pandas as pd
import requests

In [ ]:
df = pd.read_csv('dialect_dataset.csv')
api_endpoint =  'https://recruitment.aimtechnologies.co/ai-tasks'
my_json = df['id'].apply(str).tolist()
iterations_range = list(range(0,len(my_json),1000))
iterations_range.append(len(my_json))
df_text = pd.DataFrame()
for n in range(0,len(iterations_range) - 1):
    r = requests.post(api_endpoint, json = my_json[iterations_range[n]:iterations_range[n + 1]])
    df_text = pd.concat([df_text, pd.DataFrame({'text':r.json().values()})], ignore_index=True, sort=False)
    display(df_text.tail())

                                                  text
995  @NABAA71243942 لا عيني هاي هسه هيج صارات قبل ت...
996  @NABAA71243942 اي لان فاسد لان جاي على الفساد ...
997           @NABAA71243942 ما بقى شي اقصد من العمر 😂
998  @aarrawi والله نتيجة مجتمع تعبان يعني المعدل م...
999  @NABAA71243942 لا والله مو المعدل الخلل الخلل ...

                                                   text
1995  ليش عدنه يعقدون الطالب ويفرضون عليه قوانيين وي...
1996  واني واصل مرحله بتركيزي بيك اكدر احسبهم رموشك ...
1997      شنسوي هسه بآخر يوم من السنه ؟؟ نسوي مصيبه ؟ 🌚
1998                 @k4r00m راح تسمعون هالبيت هوايه 😂😂
1999           @Eman_iq 😂😂😂😂 راح تسمعوه هوايه هالبيت 😹😹

                                                   text
2995  @ai1995_2018 @A077221 @noor_0876 الله يبارك بح...
2996  @Mu_AlSadr مع الاسف سيدنا  خلي نشوف محنتنه بالاول
2997  @MK7m1EqfzrdXYYr @wewew1633 الله يبارك فيك باش...
2998  @ymry12 @tasmimALgantin @Rojjjj___14 تسلملي ما...
2999  @selectd1 @AI_iraq_GP @wewew1633 الله يبارك بح...

                                                   text
3995  @wwwalldotnem @EngFrank4 @sayaliraq هلا خيتو ل...
3996    @ranra_21 بس إلا تسويها مره ثانيه ههههههه تسلمي
3997  هسه كلنا نعرف ينسى القطن والمقص بالعمليات أخو ...
3998  ♡̷̬̩̃̊▬▬▬▬▬▬▬▬ ✾⁐🌸͜⁐✾ ▬▬▬▬▬▬▬▬♡̷̬̩̃̊♡̷̬̩̃̊\n\n...
3999            @ranra_21 هههههههه هسه وكت تحشيش هههههه

                                                   text
4995  @zaed_napol9 سلامة والدتك زيودي عدها العافيه ا...
4996       @al__alway @drwihda ليش هاي الكاوليه دكتوره😱
4997  @a_7_m_7_n_7 هذه بس الجعجعه مابيهم حيل للحرب ر...
4998                    @AnoHarthea فضيع هذه فعلاً مبدع
4999                     @luoiss_l شنو من تضيع وقت وسخف

                                                   text
5995                 @M_iq_99 ارتفع ضغطي وانه مالي شغل🙄
5996           @M_iq_99 😂😂😂😂😂 يااا هاي شلون نرهمهه بله🤣
5997         @Abdulazizluies يمكن انت اللي انا ناطر !🕊💕
5998  تعرف شنو احساس الگلب من يسمع اسمك ؟\nأحسه رايد...
5999                      @_642__ يا الله شنو هالصوت ❤️

                                                   text
6995  اكيد الايام دواره والي مايدري اليوم يجيه يوم ي...
6996  @sonik75439 @Death_To_iran اقولك أترك ايران وت...
6997  @sonik75439 @Death_To_iran اقول الظاهر عايش بك...
6998   هذا هو مذهبهم رياء ونفاق https://t.co/LvfGfNG3GN
6999  احله اغنيه تركيه مال الباشه حزينه وحلو تحداك ا...

                                                   text
7995  @abo12osama @aliahamad945 @mustafakamilm صدك خ...
7996  @moonnor27 @ialwesam خلهم يكتوون بنفس النار ال...
7997               @miss_nouraq8 وشنو بيهم عيب البعثيه؟
7998  شنو الفائدة من هالمعلومة مستمتعة بجلد الذات شن...
7999  تعاطفنا ويه نادية مراد لأن المسكينة تعرضت لأبش...

                                                   text
8995             @XuQq8g8kunmKTEy لاتعلب حباب بعدك جديد
8996    @r_man3_20 النظام قوي جداً ماينجح اذا انقلاب صح
8997  انت من وين طلعت قبلك اني ما عشت\nعمري ما شفت ا...
8998  شعب راقي وصاحب تاريخ وثقافه يستاهل  #كاظم_السا...
8999  @baligh_ya هسه تخلي نفسك بمواقف بايخه يااخي لو...

                                                   text
9995  @LowiSahiNazal @YouTube لؤي ساهي مغررد ١٠٠ تغر...
9996        @ALASHKAR_RT كوميديا (فشخ)كما يقول المصرين😄
9997  @MethaqAlFayyadh ما تعرف ليش؟؟!!!😉على أساس زعل...
9998  @NatGao_Arabic @nippon_ar ممكن الرد على الموضو...
9999   @MethaqAlFayyadh صحيح وهسه وصلو قرب فندق شيراتون

                                                    text
10995                     @mhgsdfg صباح الخيرات يسلم حسك
10996  @ALAHLI_FC عمر السومة لازم يلعب بداية الشوط ال...
10997  @MAJEDALKHELAIFI شنو الاشكال لو الضرر بالموضوع...
10998  @Benayadachraf خطية رونالدو ما يخليكم بحالكم ي...
10999  @MAJEDALKHELAIFI هذا لاعب ما يلاعب عفيف المايسترو

                                                    text
11995  البعض جاي ايحاول اغير التاريخ و يبيع بطولات عل...
11996  @Mohassad71 ترة كلامك مو دقيق اكو من اموصلك فك...
11997               @GAMILA24149969 لا بربج 😲\nجه\nجاهلة
11998  @Ccoktaill هذا المعرس راح يأجر القاعة اسبوع وي...
11999  انتو صدك تحجون مي بارد نزل على كلوبهم ط\nابتلي...

                                                    text
12995  @AFC_AW7 الباحثون عن الريتويت\nع الاقل ما يقول...
12996                  @TalalPost عشان يلعب كرات طويلة 😂
12997  @Rana97Ja29 عيونك الحلوين 😅\nخلال الشهر القادم...
12998  @Abukalabcha يعني العالم كله يصرف ولاحقين مانش...
12999  ههههههههههههه بطتنا بطت بطن بطتكم بس بطتكم ما ...

                                                    text
13995  صورة 360 اخذتها من نفس المكان\nالمسافة اللي قط...
13996  @_SARA_IQ ذبحني الخباز كومة يطلع بحديقتنا الخل...
13997  @Zh_FCB يمعودات لا يتعاركون بالطيارة ويكلبوهه ...
13998  @mn9or1313 @fencers1978 @HusseinY22 اعطيني روا...
13999  @mn9or1313 @fencers1978 @HusseinY22 خذ وقتك ال...

                                                    text
14995  I added a video to a @YouTube playlist https:/...
14996  I added a video to a @YouTube playlist https:/...
14997  I added a video to a @YouTube playlist https:/...
14998  I added a video to a @YouTube playlist https:/...
14999  I added a video to a @YouTube playlist https:/...

                                                    text
15995  @TamyAlbadry الله غالب ..ولا وقفن الدموع كل ما...
15996           @AhmedHadia74 امتى هالعار هذا توا قصدكم😱
15997             @AliZobi51 كتبت فيها واجد اخبار بنغازي
15998  النية واصله لخبطها في بعضها🤣🤣 https://t.co/dQm...
15999  @CJ5B4HHvR3y5iQv اذا انا من 2014 بس وقفنا العم...

                                                    text
16995         @3bdurrauf والله عظيم وجعتني ربي معها يارب
16996  #خلوا_فيها_شرف_الزف احنا نضربو مع اللي يضرب. و...
16997  @MG41034 ان شاء الله يكون فصل بس ,,اني كنت عاي...
16998  @MG41034 هدم اهل الخليج مايعرف ربي راهو شوف شن...
16999  @anwerbenali77 فدوي القلالي مديعة في قناة الحد...

                                                    text
17995  الشعب كله يبي يرجع للظلم الصراحة عيييوووو من ا...
17996  الرفقه الأمانة على اساس فضحونا قدام العالم الم...
17997  السراج وغيره من النواب وولاد ستين كلب لما يساف...
17998  كمية حقد بعض #الشراقة على الغرب تبي علاج نفسي ...
17999  @zNH11MJd2bQidyp حبيبتي ربي يحفظك وكلنا خوت وا...

                                                    text
18995  @TahaniM92 مادل سنة وانت طيبة تعاني ، عيدكم مب...
18996                 @boogy44_pep وانت بخير ان شاء الله
18997  تقريبا نص ساعة في الدوش نطلي و نعاود و نكد بلي...
18998  معناها فيمانزم ماتبيش تتزوج باش ماتجيبش صغار و...
18999  @AbsRadan عيدكم مبروك و كل عام وانت حي بخير وي...

                                                    text
19995  اللي حاب يتسلطن #اصالة  تغني #جرح_ثاني ل #شيري...
19996  #عمرو_اديب يعني كل حلقة بتجيب سيرة #احلام حاب ...
19997  محاولات فاشلة ل #عمرو_اديب حاب يورط اصالة بتصر...
19998  @Mmmlss7  احلام بتحب ان اللي يغني خليجي يكون خ...
19999  @Mmmlss7  قالت هذا رأيها بس لكل شخص وجهة نظر ه...

                                                   text
20995                  @I3avari هذكي خمسه من لوطه بكل 😂
20996          @LasfarDama انا ملك الزعبطه كنت 😂😂😂🤦🏻‍♂️
20997                     @BobAB7 في قهاوي الكيش يالجرب
20998      @alialfellah 💚💚💚💚💚 احلى عليوه وحق الله ايامك
20999  @HammadyJuve احلى بن ولله لنقنك متعه خلك من الدي

                                                    text
21995  مهند😂 كنا ديمة نتعاركو ع اتفه الحاجات https://...
21996   نبي يوم ٢٠ يجي ويمشي بسرعة عشان نبدا ف dark 2 😩🧡
21997  @happilylola حتى انا اقسم بالله بكل☹️ ح نديرو ...
21998  @Hakim98FA والله م نندري عقوري ولا لا😂😂😂 بس هو...
21999  @Hakim98FA دمدمه لنقنه وديمة نتعاركو ع من يجاو...

                                                    text
22995  كان قالها صلاح بادي نساء طرابلس سبايا تشوف الل...
22996  قوة حماية طرابلس قالولكم السراج يخنب واحنا مش ...
22997  رحمو علي صاحب الكوشه اللي مخلي البلاد مفيها شي...
22998  مش عارف شني خطرله علي أساس القوات تتقدم والفيس...
22999  رافعين العريس والعروسه لابوظبي يبوهم يرجعو لبع...

                                                    text
23995  يانورة  الميعاد ليك  اشتقنا\nمن غيبتك غاب الهن...
23996  @hacare جونا دكتوارة من امريكا وخبراء من ناسا ...
23997  ولما وصل حال ليبيا لما هو عليه الان. https://t...
23998  @hnanomar مش لازم تسخني \n30!ثانية بعد التوليع...
23999          @rUvf8Gjo7yiuyaN روابط مفيهاش ثقة يا احمد

                                                    text
24995  يصيمو ويصلو ويقطعونا معاها كن يقعدو كفار ارحم ...
24996  الليبيين بصفة عامة يحبو اللي يعرمهم دوة واوهام...
24997             مفروض الكاس عطوه للمعلق عليك ثقالة ازف
24998  @hamza_alwerfale @AlfakhreyB خول صار \nي بوحا ...
24999  يتعبو مع البنات والبرجوازيين والمشكلة تلقاه مش...

                                                    text
25995         @7Obidy @ehabalamami ماسك ادمن الطحان غادي
25996  @SonousiElsagezl كانكم متعودين عليها انتم هذي ...
25997  @Sloma_Almahjob فتاريخ التنس فيدرر ياصديقي ..و...
25998                @AsloomaSasi كيف صار مسح شامل قالوا
25999  شينك دنيا وشينك وقت ، الله المستعان ولا حول ول...

                                                  text
26995               @Aishali_tre تكلمتي موخر الله غالب
26996                      قلبي ليك هدية ومش خسارة فيك
26997             @geloshe2006 ربي يواتيك بالوقت الطيب
26998             دكراك مرتني بصمت  وجاء على بالي كلام
26999  @fafy308 باه فازو النوتيلى تبيه بعد متمووو😂😂😂😂😂

                                                    text
27995            الله يكرهك يا حكم الله يكرهك الله يكرهك
27996  @AnoosBenomran لوبيتيجي قبل نزل رفسه 😂\nبس حار...
27997    @MoAhlees مرطزها يا راجل و قتل المباراة و خربها
27998  @MiDoMJaRaI @IbrahimFarag89 انقنه داره ديره تح...
27999  الصاحب اللي ماهو راضي عن أسلوبي \nلا يحسب إني ...

                                                    text
28995                  @Many_elagily خخخخ كلاب حشاك كلهم
28996                @hnanomar ههه عليك قصه هالضي عالصبح
28997  @hnanomar هههه يستر الله عالصبح وحمو واجازه حر...
28998  @farajAlmadani يقولك الشمس فيها كل ثانيه انفجا...
28999  @Mrs_Gibberish صح كبرها تكبر تعامل معاها بتفاه...

                                                    text
29995  @khalid_Enpaya والله ما كنت مدورتهم ولا شاقية ...
29996  @discreet1981h كلام كبير قاله خسارة ما كنت نحس...
29997  بالنسبة ليا كسره واللي فات فات 😑 https://t.co/...
29998  @discreet1981h نراجي في طلعتهم من الابطال بس و...
29999  @maahdeee ممكن هي قصدها انك ممكن تكوني ربة بيت...

                                                    text
30995  @LyConsigliere  احب لنفسي كما احب للغير مش مهم...
30996  @hesham22_hesham ان شاءالله ربنا يفرحك و يكون ...
30997        @_che___   مابه جديد الا انت ..بصوت احلام 😛
30998  @7ssry @E_i2i إذا كـــان ربُ البيتِ بالدفِ ضار...
30999            @Sirte_pride01  يتزوجهم جن يكسر ارقابهم

                                                    text
31995  الصيف خش و رمضان قرب اللي عنده مولد يوتيه و ال...
31996  1 _ خلونا في الحاضر اللي صار في عهد معمر صاير ...
31997  3_ لازم من المضي قدما ياسرها لعند امتي تقعدو ا...
31998          @almhwoos ماشيه الامور ف نعمة ، شن اخبارك
31999             @almhwoos دفاع الرئاسي علي لسان الغضري

                                                    text
32995                    @khalidenpaya فيه جو اضحك وخلاص
32996                  جينا للنوم .والنوم مابا ايجينا ..
32997                 @lol_warragh فيهاش طعمه الزرده هكي
32998  @lol_warragh هههه الجو كله انك اتنوضي تلقي حاج...
32999  @huda__libya عنجدا كان غير انشق وغناله اغنيه ع...

                                                    text
33995  @heaven_smiley ايه الصياعه الي انتي فيها ده   ...
33996  @NASSERAMMARI يسكر علي السيراميك     زى لكلاب ...
33997  @BaFQNVZ88ginF3m لما قامة ثورة 17فبراير قعد يع...
33998  @EntssaarEldresi @khulod_amer انا ونتصار نحبوك...
33999  @hnanomar يرتو فيهم غادي عندهم   و يدزو فيهم ل...

                                                    text
34995  @ShoSho75253579 أن شاء الله يارب،،شاطرة ماشاء ...
34996  @ShoSho75253579 عارفة شوشو والله،😔،كملى هكى وب...
34997  اصلا معو حتى الصمت احلى من النسمة ❤ #اليسا😍 ht...
34998  ايه .😍😍. أحلى زوز عرفتهم في حياتي🌹🌹..ربي يحفظه...
34999  @arabqoute نصرخ بصوت عالى ولو قدامى حاجه نضربه...

                                                    text
35995  خطير جدا ومهم ومؤكد خاص #الخال_الورشفاني \n\nا...
35996  طبعا اي كلام ينشر من منطقتي ورشفانه من مصدر مو...
35997             #صبراته\nتناديكم\nياااارب سلم الابرياء
35998  الله اكبر ولله الحمد تم القضاء علي الازلام الب...
35999  مش قلنا راهو يلي صائر في صبراته مشروع للمصدي ح...

                                                    text
36995  #مرات إدير كل الحاجات الحلوة و الجميلة 󾌵 للشخص...
36996  انكــــان الغـــــلا بالكف انشلفــــــط عزيـــ...
36997  بيــمر و بسرعــة بيصير اليوم .. أمس .. \nايقول...
36998  #سيلفي من فوق مبنى كلية الطب البشري  󾌲󾌸󾔗  \nكي...
36999  بعض الناس عقلهم "̮*\nزي ﺎلفستق ﺎللي مسكره من ك...

                                                    text
37995  جمهور الميلن مساكين  عايشين ع ذكريات الزمن الج...
37996  @IdreesAlgwie1 هههههه مافيش داعي لهذه كله انت ...
37997                          هلبة ع كبير الطليان والله
37998                @AishaEndari منو مزعل نوارة التويتر
37999  @knowwhathappenجمهور ف الملعب اقتنع    وصفق لك...

                                                    text
38995  @amal74419016 انا لله وانا إليه راجعون انصدمت ...
38996  @amal74419016 توا بس فتحت النت من كم يوم كنت م...
38997  صباح الخير او فطور بيتي 😍 https://t.co/UcVjnyGhG7
38998         @AElbuzidi يسلموا استادي كيف حالك ليك وحشة
38999  @S_Elhenshiri الحمد لله علي سلامة الوالد ربي ي...

                                                    text
39995  اللي ينزل في صورته مع الحولي و هو علي اساس يذب...
39996  @knowwhathappend نبيها بيضا و طويله و رشيقة يا...
39997  @IslamTosha اللي خلف ما مات يا توشا ..\nملتقاك...
39998  كنت هشربها مسكره لولا التحذير هذا https://t.co...
39999  الناس اللي لا تحظر في الذبح لا السلخ و ما يليه...

                                                    text
40995  @Nayed_Mar يا ترى التارك او المتروك هو اللي ين...
40996                       اللي ما جاش ليبي نجوته كبيره
40997                   @Nayed_Mar  انا نسأل فيك عن رأيك
40998            @z71SM7qoLIrGpr7 تي نحن زوا علينا الفيل
40999  الله يجبر بخاطرك يا شيحه 😊😊 https://t.co/QGYqo...

                                                    text
41995                    @H_a_neen يصلح عادي بس يبي اسطا
41996  @H_a_neen والله في طرابلس مانعرفش بس ماتخفش يص...
41997  @H_a_neen ماتخفش ساهل موضوعك تو نشوفلك سطا ونقولك
41998  @HaifaKresh نصبر عادي في اولويات يعني فرضنا ال...
41999  @HaifaKresh الحمدلله علي سلامتك وانا نقول كنها...

                                                    text
42995  @JuveNajeb اغلبهم هك والله و نحساب روحي انا ال...
42996  @ZEldrsy عيت فور و مزيز و انتكة و تحكوا عالفلو...
42997  @ZEldrsy 😂😂😂 نحكيلكم انتو الاثنين انت و الخول ...
42998  @ZEldrsy @thedeee___ أنا أراه عائليا الموضوع أ...
42999  @itz_Islam7Fathi ههههههه انا اللي معبرك في هذك...

                                                    text
43995            @NASERELGAZALY انا جيتك فايبر ليوم هههه
43996  @Fatto_Ju اهو قاعد بلبسة الاحرام 😂 https://t.c...
43997  @jndiakk18 اهو بلبسة الاحرام والمعسل يبكبك 😂.....
43998         @AEmsik لان اسمها سهى مش ابوبكر ولا احمد 😉
43999  تخايل عندك نقال ملك النوكيا وتبي تصبله تطبيق ي...

                                                    text
44995         مرايف عل فطرة يلاهم\n.ناس اعزاز كبير غلاهم
44996  اوعي اتخلي قلبك ابيض\nلانه حيتوسخ بسرعه ياتيمو...
44997  سبحان الله مش عارف\nليش الشخص لما اتشوفه في شا...
44998  ياجماعة في حد حاس\nبارتفاع الاسعار اللي نحنا ف...
44999  ياجماعة كان #الدولار\nبيقعد هكي سعره انصكروه ا...

                                                    text
45995  انشالله الفوز لمصر العروبة يارب https://t.co/V...
45996  إندالن ايام الكرب و غابن ايام الرخا\nو ايام كر...
45997  حسبي الله ونعم الوكيل فيهم يحشم فيهم الشعب الل...
45998  ربي يشفيه ويعافية وحسبي الله ونعم الوكيل فيهم ...
45999  @AbdallahAtamna انشالله توصل بالسلامة وانت فخر...

                                                    text
46995  فاسكيز فاسكيز 😍😍 رجل المباراة بكل تأكيد ويأتي ...
46996    @match_today_10 طيب وعلى الدونغل شن حيكون وضعها
46997  @ana_noon48 توا محطة شمال بنغازي كاتبين black ...
46998  في مصطلحات عنصرية يتحشم الواحد يقولهن تلقى بنا...
46999          قالك ما شفوهمش وهم يسرقو شافوهم وهم يرضعو

                                                    text
47995  @Dia83030497 @MatogSaleh ياماما ياعسل ماعندي ل...
47996  @Dia83030497 @MatogSaleh ههههههههه شكله نعمان ...
47997  @MatogSaleh @Dia83030497 ههههههههه مفهمتش من جابك
47998  مره نشبه لشاعر علي الكيلاني ومره نشبه لي طارق ...
47999  @Dia83030497 @MatogSaleh هذا رايك ويخصك انتي ت...

                                                    text
48995  @Mmmmmmm09044531 التويت امتعك طلعلي تلاتة شيبا...
48996  @Bombermuller وين العزاء خلي نمشي نعزي ان شاءا...
48997  @Dr_Emyalgrary @je_soahmed ياريت العداب كله هك...
48998  @Bellalo81978443 ههههههههه جمعيهم مع بعض وحققي...
48999  @mohammedawaad بالنسبة لمنطقتنا مايخافوش القنو...

                                                    text
49995      @omElsgar ياريت يعلمونا ولا يعطونا كورسات 😂😂😂
49996  @omElsgar أنا عيلة وحدة والضي مافيش وما فكرناش...
49997         @Nadia_A_sh ربي يحفظك \nأنا حبيت الحق ❤❤❤🌷
49998                  @justme1187 كانت أحلى سنوات حياتي
49999  @dinonutellar النكد حاجة فطرية عند الذكور بالع...

                                                    text
50995            @al3broodly @aldale66 برا يا ولد القحبه
50996  @star0065 اتقي الله الجيش مش يهود فهم ليبيين ا...
50997  @kwifya عاوزين طنجرة أصل طنجرتنا طنجروها العويل 😀
50998             @LibyasChannel معاهم سمر بوحلفايه زعما
50999                   @linabenhalim بس لازم من التفتفه

                                                    text
51995  @qahwa_r @RayanDadysGirl كلام جميل ريان اكيد ه...
51996  @UAE_kalashinkov @monaalyafee @almayassahamad ...
51997  @UAE_kalashinkov @monaalyafee @almayassahamad ...
51998  @Alsh30002 @lawquqa @AnwarGargash وين انت رايح...
51999  @1397Hma @almayassahamad @jaberalharmi ياخي ان...

                                                    text
52995  @ELGENARAL2 @AlthaniSuhaim الله فكنا شرهم عوذه...
52996  @20fourMedia بكره اصور لكم شوارعنا المكتظه ياك...
52997       @hassanalishaq73 يبي يصير cool \n وجه الكلفس
52998  @3issaqtr بكره تطلع تقول انا عدوي الحمدين و اح...
52999  @Soor_Alkuwait و خويّك ليش عطاك الفلوس القطريه...

                                                    text
53995  @mse1438 @CNBCArabia اقرب حليف تخلى عنكم 🤣🤣🤣 h...
53996  @mse1438 @f8_f3 @CNBCArabia أخرتها طرش بحر . و...
53997  @aliali000yuip @aborashd002 ياغبي قلتلك واقع م...
53998  @aliali000yuip @hotmanyes @aborashd002 المصخره...
53999  @C4aIz60UvSzltTt @AbbasAlmaskary انسميها القرب...

                                                    text
54995  @Me_YLJ @nashwaa @abudhabitv ما عندك بلاد تنضم...
54996  @AricTwasul @hassanalishaq73 @mohammad26qatar ...
54997  @w7vv7w اي حبايب السيسي بنزل اغنية أوعى ياسلما...
54998  @aiaa19861911 بتقول هذا الكلام عشانك في السعود...
54999  @aiaa19861911 ياجبان خايف على أكل عيشك حلوة في...

                                                    text
55995  مع نفسك ولا راح تشوف مني ردت فعل يعني تكلمت ول...
55996  الساني يقص الحديد بس ماردع المتخلفين \nوالخبلا...
55997  @ahwa_3yonh @Khomene1 انتي ياعنز الأمارات خليج...
55998  @ahwa_3yonh @Khomene1 خلي منج السياسه وانتبهي ...
55999  @shoosh4_ @Khomene1 ماراح ادعي عليج ولا انزل ن...

                                                    text
56995  '\n\nفكرة #استاد_راس_أبوعبود رووووووعه ❤\n@roa...
56996  '\n\nيا ضروسه ..\nمن اللي علمّه يكون سوسه ؟! h...
56997  @falsaai @SidraMedicine @PeterMorris41 @TrishM...
56998  '\n\nلك الحق تمشّى بين شعبك .. \nاللي يحبّك .....
56999  @ahmedalkuwari10 @ABZayed من نعسة جفونه ..\nتع...

                                                    text
57995  @Jassimbinhamam عيال كلب كلهم  منافقين والله ع...
57996  @Mubarak_Gen1 ههههههههههههه لا وزياده بعد ماير...
57997  @khalidalkhalifa ياخي يعجبني هالانسان يدري انه...
57998  @BoHomoud007 بوحمود لاتستعجل السنه الجايه يمكن...
57999  مايكسرون خاطري الا مشجعين مدريد يشجعون امس الي...

                                                    text
58995                   @JBT_86 معتبرينه كنز وطني ثمين !
58996  #الغرافه في مهب الريح !\nاللهم الهمنا الصبر ع ...
58997  اللي قاعد يصير في #الغرافه استهتار بتاريخ النا...
58998  @AAzizAlJanahi @al_khaldi_777 انا احسب كاسميرو...
58999  @bobader1973 عندنا الحاج فكل شي ممكن عادي ترجع...

                                                    text
59995  @mohdalsowaidi7 يالسويدي اشرايك فس المثل المصر...
59996  @AlrayyanSC مهب سوزا لو مخلين خالد عثمان مدرب ...
59997  @AnwarGargash يضحكوني بعض الشعب السعودي الي مس...
59998  @m3takl تعال يانواف على عز وكرامه .. \nلبلاد م...
59999  @rayan_1gh لو يلتفت عليه بوحمد  يمكن تجيه الدو...

                                                    text
60995  @AMAG596 @Kuwaity__7r وليش خاشينها صناع القرار...
60996  @Kuwaity__7r والله انا احنا ساكتين عنهم فيهم ذ...
60997  عدال يامحور الكون 😂😂 \n\n #لا_لسفر_السعوديين_ل...
60998       كيفهم. شتبون فيهم  \nالمهم يفارجونا في السعه
60999         @alkhuzama صباح النور \nمافيه الا كل خير 💕

                                                    text
61995  @ali_ccq @GMS_3N @ccqstudents هاي تعطي الانجلش...
61996  @Alhan0ufAlajmi_ @ccqstudents اخييه الله يعينك...
61997  @Bo_ja_philo48 @Alhan0ufAlajmi_ @ccqstudents د...
61998  @NAlhaidous @ccqstudents يارب بس تبي اجوف معدل...
61999  @_H2701 @Dam3t7oob @ccqstudents ماس كومنوكيشن ...

                                                    text
62995  @capbahman @abu_kreem1 @Dstorna @lolwa_alabdul...
62996  @capbahman @lolwa_alabdulla @abu_kreem1 @Dstor...
62997  @lolwa_alabdulla @capbahman @abu_kreem1 @Dstor...
62998  @abu_kreem1 @capbahman @lolwa_alabdulla @Dstor...
62999  @capbahman @lolwa_alabdulla @abu_kreem1 @Dstor...

                                                    text
63995  @NooraBintA اخخخ يخلونج تكرهيين الشي الي تحبين...
63996  @_Mashaaeel @saraahammam الدبة الصجية اليي ماخ...
63997  @_Mashaaeel تنامين وتقومين و تنامين وتقومين وت...
63998                    @JojaYousif انا فهمت شي ثاني 😂🛁
63999  @JojaYousif اعطيج عيوني حياتي 😘 لو انج فابتدائ...

                                                    text
64995  @Mohmd01y1 @jaberalharmi انت تسمع ترامب وهو كل...
64996  @x_m769 @A_AlAthbah يا رجال هو ما عز نفسه، تبي...
64997  @MBS_KSA90 بشرط اذا مافي قرارات تسمي نفسك #شري...
64998    @Roo7__qtr @ayoonalkoon_ مسحت الفيديو مو موجود🙄
64999  @Roo7__qtr مرات الواحد تجيه فترات يترك كل شي، ...

                                                    text
65995  @LiVERP00L_5 @Alawy_995 فهمتها الحين بعد ما وض...
65996  @HfcHilal57 @madridinews1 @S_Alshdadi والحين و...
65997            @ALANSARI_AHMD جاب كاس اسيا للشباب ٢٠١٤
65998                 @fares_316 هههههه انت منجن من تالي
65999  @MrRossonero والله اني اعشق هذا الاعب ♥️ وللحي...

                                                    text
66995  @SsMedic7 ماجد كم مره اقوللك انتقد بدون الاساء...
66996        @SsMedic7 انت فاهم كلامي وماله داعي الطنازه
66997  @meeme_ae وانتي شكو كلام بيني وبين ماجد انتي ش...
66998  @mariam_al199 @liferdefempire @JoaanBinHamad @...
66999  @limo0o0nah01 @1111_amas @Dhahi_Khalfan يعني ا...

                                                    text
67995     @M7MD_RASHID ممكن أعرف انت أتكلم من يأخي ☺&gt;
67996  غآبت الشمس وعسىﺎ اللـہ يمسّينآ بخير       جعـل...
67997  غيري أصاب و المخطي أنا .، آه من جرحي اللي ما يطيب
67998  مالي على الناس لا فضل ولا منہ .، ولو شفت فيني ...
67999  وﻣن ﺻد ﻋﻧيء ﺟﻋل رﺑي  ﯾﺑﯾحه .، ﻣاﻧي ورىء ﻅﮪر ﺎﻟ...

                                                    text
68995  @fahad3jlan خله يادب اربع الاف حوثي بالاول \nث...
68996  تغريدات الذباب فالهشتاق نكته🤣\nاخذوا Update\nا...
68997  @SalahAlelaj اخوي صلاح ... ٧٠٪ من  تغريداتك صا...
68998  @SalahAlelaj اووووووووووووفر تغريداتك عن قطر و...
68999  @RTarabic الصياح على قدر الالم \nلو انها حماقة...

                                                    text
69995  قطر فيها وفيها وفيها ، احنا راضيين ، دول الكفا...
69996  @Mub1981 @mlam7yosfia7 @aa__bq @aljahane @uae_...
69997  @saudq1978 يقولون وقتها كنت تبول في هافك 🤔 من ...
69998  @Dhahi_Khalfan هذا تسأله عن وكر دعاره ولا خمار...
69999  @Kuwait_okk الف طز واحنا الربحانين والله ،، ون...

                                                    text
70995  @alldxb @nasser19999 انت من دايس على ذيلك .. ا...
70996       @SHW4G4N شهالاشكال الخايسه اللي تسمعين لها 🤢
70997            @SHW4G4N بسوي لج بلوك لين تخلص الازمه 🤢
70998  @R_bahraineya @nasser19999 كلهم فريق واحد و يل...
70999  @emiratessport @MAJEDALKHELAIFI القريه العالمي...

                                                    text
71995  @AJArabic يااا جماعه احترموا ال١٣ مطلب شوي😂😂😂😂...
71996  @Ksa20302020 @Jaber__Althani @ElegantQtria يال...
71997  @ashash99133 معلومه بوهامور مب سجن ،، بوهامور ...
71998  @hashim010101 @KsaBrk ليش يهال!؟ ماتقدرون تاخذ...
71999  @adelalhajaji والله هذا الممثل مسكين ،، جنه مر...

                                                    text
72995  @0g0GwHOSt0Fvn2o @Modhayani1001 صح كلامك حنا م...
72996  @Modhayani1001 @0g0GwHOSt0Fvn2o ليش تتهربون ما...
72997  @Modhayani1001 @0g0GwHOSt0Fvn2o عزمي بشارة مفك...
72998  @Modhayani1001 @0g0GwHOSt0Fvn2o يعني تركي وناس...
72999  @Modhayani1001 @0g0GwHOSt0Fvn2o شأن داخلي ولكن...

                                                    text
73995  @Nassrwy09 @Yahya_s8 و نحن في #السد  محتاجين ا...
73996  @o7it_ أبشر و أوعدك أن #السد جايكم على الموعد ...
73997  @Nassrwy09 @Yahya_s8 الهلاليين كلموا #الزعيم #...
73998  @saleeem22052 @LPHXg2bkoSLUsxW @Fc7rkM21oUbmEB...
73999  @o7it_ خالصه من الرياض بأذن الله حاضر بحاضر ما...

                                                    text
74995  @h_alfala7i @QATAR_7 واقري بعد من كان يصرف على...
74996  @h_alfala7i @Tomy_qatar82 يا سبحان الله يعني ا...
74997  @h_alfala7i @Tomy_qatar82 تاريخ كله ذبح مذابح ...
74998  @h_alfala7i @QATAR_7 يا حصة لا توهقين عمرج انت...
74999  @h_alfala7i @QATAR_7 اما اذا تبين تسبين وجيه ب...

                                                    text
75995  @saudq1978 #ارحل_ياتميم ،،،،شف حدا بزرانا ياسع...
75996  @alkhames ينتبهون ربعنا هل الكويت ترا ماوراهم ...
75997  @JoaanBinHamad ذيبنا والظاهر انه ياكل الحشيش  ...
75998  @NasserSalmeen والله ياناصر وش عليك ظاهرة النع...
75999  @Saleemhhhh @Boabdelrahman1 ماقصر الملك سلمان ...

                                                    text
76995      إنحرف كما شئت ولا تبالي     ف جميعهم منحرف...
76996  ﯾﻗوﻟون ﺧل ​ﺎﻟـــﻗﻟب ﯾﻣﺷي ﻋﻟى ﺷﻓﮬ وﺎنا ﺎﻗول مّ ...
76997  ععلىىّ ῑللهَہ هَ يااِ / ﻣقااِدير ..          ...
76998  ﺂﻟوﻗت ﯾﮔﺷف خاﻓي ﺂﻟﺣي وﺂﻟﻣﯾت وﺂﻟخاﺳر ﺂﻟﻟيُ ماﺷي...
76999  ماودكّ تجي بالصدفه وتقول فاقدكَ ؟  بس أدري عدي...

                                                    text
77995  @maya22scream @saloom_80 @KHK شف من يتكلم عن ا...
77996  @NaseerHaia @Mubarak_Gen1 @anaswahalaa وضعنا ا...
77997  @Bintalnaimi45 مانرد على النعاشات 😄 والكلام لا...
77998  @ETMAHALI @JnAlMarri ازعجتونا بالقناه الوهميه ...
77999       @AlthaniSuhaim أحسن تغريده شفتها منك 👍🏻 ادعس

                                                    text
78995              @nawaf00965 طبعا نظام وترتيب في كل شي
78996  اذا حد يسولف علي بسالفه قالها مليون مره https:...
78997  ههههههه ايش نسوي بعد الله يهدي الجميع https://...
78998  @abukarsh2018 ياجماعه بدون استهبل جد ليش يلبس ...
78999  @AlrayyanSC اقول صفقتين عندي عبدالعزيز حاتم وخ...

                                                    text
79995  @khalidjassem74 @Rero_Ooj الي مبسوطين عليه ويم...
79996  @marzoqi_w اصلا عيب يحطونهم يتهمون بعض في برنا...
79997  @marzoqi_w الإحصائيات تطلع بعد كل اختبار في ال...
79998  @p__Jl @Rashid_Alkuwari @khalidjassem74 احترمت...
79999  @Abdulkhaleq_UAE وانت ليه متضايق !!؟ وانت قلته...

                                                    text
80995  @JoaanBinHamad الشفت الى مداومين الحين من  الذ...
80996  @Alaazaem666 @shafi_s_alshafi يالخبل انت مهبول...
80997  @qataar_1 صدقتك يالقطري 😂 والله المشكله الذبان...
80998  @Sh3aib ياخوي احنا نحبك لصراحتك ونزاهة طرحك ما...
80999  @TamimBinHamad في مشيتك كل العالم يتبعونك\nحنك...

                                                    text
81995  المتضررين هم شعبكم ولا القطريين هم اللي يمارسو...
81996  @601091a56e20451 وينه وين صب القهوة هذا حده يض...
81997  الأسبوع الجاي قلوبنا مع تميم وحمد واحد 😂😂😂😂😂😂 ...
81998  @waseem_yousef زق في ويهك .. الشعب القطري قاعد...
81999  @enaaad98 @Rola_4ever شكل شنبك متجمد عقاب لك و...

                                                    text
82995  @bilalmarey. أنا فكرت انك شفت الحلقه بس عشان ا...
82996  @taghared إذا تأخر على الطلب.  أقولهم. ليش تتأ...
82997  طيح واقف ، مهما فيك الوقت دار  بيع من بآعك وإش...
82998  @taghared كلامي لرجال الأعمال مجروح. لأني. من ...
82999  @taghared. صعب لما تكون مستعجل. ؤالعكس صحيح.  ...

                                                    text
83995                 بفكروني بمزح لما احكي مليش ع الشات
83996  @hadeelabuzaid9 صح كلامك لحظة احذف التويت وانز...
83997  @NoorAwadallah مفيش تارجت من غير ناس ، هتموتي ...
83998  ايوه بقى 😍 تعالووو بكرا تضيعوهاش 🎻😍 https://t....
83999       @marwanathabt @cellogaza ولو يا حب بتتفضل 😂🎻

                                                    text
84995                  @queen_shazaR انا بحكي عن حياتي 😭
84996                  @Ahmadalshayip نام لحتى يجي الصيف
84997  @Mohanad_Zbidat اصلا انا تركية وهمه خطفوني عال...
84998               اوعى تبعد وتنساني دي الفكرة قلقاني 🎶
84999  شعور انه وصلت ل الي كنت احكي انه مستحيل اقدر ا...

                                                    text
85995  تا تساعد عايز محتاج\nو عن خَدّو الدمعه تمَحّي\...
85996  أضفت فيديو إلى قائمة تشغيل @YouTube على https:...
85997                          يا حظك يا فريق المقاطعة 😒
85998  بحكوا وبحكوا وصواتهم عالية ع شو مش عارف لسة ال...
85999  ع سيرة الثلج حكوا في ثلوج ومافي والناس تحكي حر...

                                                    text
86995  @Paltn1 @NadaAkkila1 😁😂  يعني بديت ارضى ،، وال...
86996       @Nour19059363 فعلا 👍  الله يهدي البال يارب 😘
86997  @Paltn1 @Nour19059363 اسلام اسمعي ل شيرين نصيح...
86998  @Nour19059363 @Paltn1 انا متلك عساف ولازم معه ...
86999  @NadaAkkila1 اخر مقطع باغنية الأماكن (محمد عبد...

                                                    text
87995  هما اللي بعملو هيك معقول اهاليهم ما بشوفوهم ht...
87996           @emy_alkhatib 💔💔 ليه بتعملو بحالكم هيك ☻
87997  مش معقول لليوم ناس ما تعودت على الزهق مع انو ص...
87998  عيب يا جماعة اللي بصير هوا احنا هنتفرج لمتى يع...
87999  السمكة اول ما تطلع من البحر https://t.co/gShqd...

                                                    text
88995     @Jassmine_kh ياروحيي انت😍يخليلي اياكي خفاشتي💕💕
88996         صباح الخير بس انا ايش نزلني فالجو هادا!!🤦😭
88997                  @Jassmine_kh مين سنيور السنه دي💃💃
88998  طول اليوم ماشية اغني اللي عنده ضحكة زي ديه وال...
88999  جرب اخلقلك اعذار كذب وبضحك ع حالي انت لو عني س...

                                                    text
89995  لما يكون شب طويل عرض برقبته امه واخوته الصغار ...
89996  لما يكون رجال عنده ٥ او ٦ اولاد لا قادر يوديهم...
89997  لما يوصل الشب عمره ٣٠ سنة ومش عارف يتجوز ولا ي...
89998  اي والله بتقول حكم 👍\nهي حللكم المشكلة 😅 https...
89999  فس وحدة هبلة كاتبة انتو عارفين انه تبعون السلط...

                                                    text
90995  @izzat_sbakhi هو الشكل مش مشجع بس بصورلك اياه ...
90996            واضح اني زهقت وماعندي سالفة \nاروح انام
90997  @Scottyklamy متسمعش كلام حد المرة الجاية 😂😂\nو...
90998                  من مبارح لليوم صرت عاملة ميوت ل 3
90999  فكرت وما لاقيت شي كيوت الصراحة 🤷‍♀️ https://t....

                                                    text
91995  @Ola_Husseini يعني مش جد كتييير في منه الحكي.....
91996  @la_giocondaa بلاش منه هالشوق سبيكي منه بوجع ا...
91997  اوووووه الله يعين الأغنيا قد ما بنزلوا وبطلعوا...
91998  كلهم عرصات عاملين القضية شماعة https://t.co/Ry...
91999  @ranim221998 ههه الله يعنيكم كله بأجره ان شاء ...

                                                    text
92995          @Marocoo21 حسبي الله ان شالله بتنكسر ايده
92996  اللي مالهش خير في اهله مالهش خير بحد  .. صباح ...
92997  @dina_ghalayini2 ههههه الاعياد ميلاد بتيجي مرة...
92998  @RolaAwni مش متزكرة ايش لابسة بس هي امورة ماشالله
92999                           يا حلو صبح يا حلو طل ❤️🌸

                                                    text
93995            @ham00deh ههههههه بكون اختار وقت غلط 😂😂
93996                          الحقني يابا الغول مجنني 💀
93997  @Read71Aya هذا انا تا را را\nانا الربيع ،انا ا...
93998      @alashhabmoath من حكيك شكلي راح اعبط المادة 😪
93999                           هاي جاي تشطب سمعتنا #جدل

                                                    text
94995  @RMD23 ومع هيك اكثر واحد ياخد انتقادات بعد فاسكيز
94996           @Soul__10 جد يعني كروس وسط كان اخطر منهم
94997  @diaalfiqi هاد بدو كفين ، شكلهم البلاجكة تعينك...
94998  @SajaMajaida انا ايام المدرسة كنت انام لما ارو...
94999    @baro1992921 😂😂😂😂😂😂 بالعكس بوفر عليكي مواصلات 😎

                                                    text
95995  @HaniinHosaam اه ونديتو بأربع اسماء لانو الوقف...
95996         @Shrouk_at5 لحد بجد ممكن بعد كدا لا طبعا 😂
95997                   @AfanaShaza نزل التالت ولا ايه 😨
95998  انا مش مسؤول عن التركيز ازا زاد الموضوع عن ١٠ ...
95999  2019 مش حتكون احسن من 2018 \nعشان احنا مش مشكل...

                                                    text
96995           دايما بفكر فيك واستنى عنيك العمر بحاله 💜
96996  ده وحشني موت وانا ايه بإيديا والفرقة نار بتدوب...
96997  لما تكتب لحد كلام كتير وتكون مستنى رد وما يرد✋...
96998                 بكره البرم بكره البرم بكره البرم ✋
96999  يوم لحد يأمنك ع شغلة عشان الله مش عشانه تخونش ...

                                                    text
97995  عن جمال هاليوم 😍والافطار بهيك مكان بفتح النفس😍...
97996  ودراسةةةة كوام كوووام وبضل أأجل 🌚😂😂 \nبحب الزن...
97997  @HajeejSara الحمد لله 😂😂✌️\nيسعد صباحك والله ي...
97998              @ghaliaadnan91 الله يسعد قلبك ويوفقك💙
97999                @12Queendodo22 ااه مهي حدث الموسم 🐸

                                                    text
98995  أسوأ شخص ممكن تتعامل معاه ، اللي مهما غلط في ح...
98996  @SojodHelles ههههههههههههههههههههههههههههههههه...
98997  بحبش أتجاهل حد بس في ناس بتجبرني اتجاهلها بسبب...
98998         لا مش ناقصنا والله https://t.co/8xPDPrfzO3
98999  مش كل من لقى بديل استغنى ، انا بستغني من غير ب...

                                             text
99995            @wafaasilme هادا انتي مسجل خطر 😂
99996        @wafaasilme هههههه تفكريش اكتبي عطول
99997  @Razansaed98 في اكتر من كدا وناس بتحب بصدق
99998         مكسل اروح النادي \nيفضح عرض التعب 😐
99999      @DinOo00703420 هههههه بتحطي سكر يعني 😂

                                                     text
100995  واد الهرية والعجوري تعلن غداً أول ايام عيد الف...
100996  السنة الجاي رح أشتري تلسكوب وأصوم وأفطر لحالي....
100997  يزلمة بعرض خواتكم تتركو الدين بحاله!\nهالحكومة...
100998  مش مهم العيد الثلاثاء او الاربعاء او الخميس، و...
100999  لهلأ الناس ما شبعت أسوق؟ \nيلعن ولاياها من شغل...

                                                     text
101995  اللي مصبرني على حالي إنو كل العلماء كانت بدايت...
101996  @Lana96206068 قولك بكرا ح يعرض الصورة ويدوب نش...
101997  @shazawi6  ما تعيطي كثير علشان عيونك 💔لانو بكر...
101998  @RaniaShahin11😂انتي كل مرة بتطولي لما تبلشي🙊😂ب...
101999  @Lana96206068 @shazawi6  ولكو والله لا عارفة ا...

                                                     text
102995   @lameesredaa @esraa_maree تروحي على هيك عرس ؟ 😂😂
102996  @LeenEiad لييين ♥️\nبالسلامة يا رب وفصل خفيف ل...
102997  @ahat_saraiah @Cukur_arb 😂😂😂 ما أنا بقولكم الل...
102998  @Aseel_Amjad94 هاد لسه كمال موجود 😭 الله يعين ...
102999  @Aseel_Amjad94 كل حدا شاف المسلسل نفسه يقتله ب...

                                                     text
103995  كل إنسان بيدخل الفرحة والسرور علي غيره\nربنا ي...
103996  @hopeful_2030 ايه والله انجح مشرووع\nخطر ع بال...
103997  @AliZarooq الدليل أغراض رمضان ملت المحلات http...
103998  @Alwaafy11Khal @hopeful_2030 حلوة سلم نفسك بنف...
103999  @almizaniu0 @SAAA_N2016 @triggar6 والله المستع...

                                                     text
104995            @SaadDosari والنعم فيهم ربي يحفظهم 🙏🌷🌷🌷
104996  @aafnaalthani من غير ماتكون رئيس انت الأنيق با...
104997  @hassanalishaq73 @Q_l979 اللهم امين والاخ فيصل...
104998  @ANG02200 المسكن سيف ذو حدين يسكن شوي لكن يهيج...
104999  @almuhiz31 @AlnuaimiNasser1 جزاك الله خير غلطه ✌🙏

                                                     text
105995                      @Samarkhalaf8 يسعد مساك يا رب
105996                     @Hind24441 ما عليك شر\nسلامتك.
105997  @Samarkhalaf8 صدق ...ولو كان كذوبا!!!!!\n\n"دم...
105998  #استمع الى ”يا ورد مين يشتريك“ من محمد عبد الو...
105999  #استمع الى ”بفكر فى اللى ناسينى“ من محمد عبد ا...

                                                     text
106995  انا بطلب الشغلة منك مرة وحدة و مش ممكن بحياتي ...
106996                    الله كبير وعارف كل الي جواتنا 🖤
106997  @RolaBahjat هادا هبيلة بحكي اي كلام حافظ مش فا...
106998  هههههههه اول اشي انت اكيد ما تعاملت معي تاني ا...
106999  يمكن انا لو يكون معي حلول الامتحانات قبل ما اق...

                                                     text
107995  قناعاتنا في الحياة بتختلف حسب تجارب كل شخص فما...
107996  بحكو بس تشتي الدعوات بتكون مستجابة \nادعوا لبع...
107997  @HammoudaMaram حبيبتي الغالية يا رب وأنتي كمان...
107998              @MahmoudHMiqdad اه عن جد بكفي تتدخلوا
107999  اللي ما بتقبل شخصيتك عادي مش\n ضروري تقنعه ما ...

                                                     text
108995  لو سكرو المعبر على #العاروري ! \nتخيلو يكمل حي...
108996  واحد بيحكيلي بشوفك مبسوط اكتر من اليهود ! \nقل...
108997  بديش ولا حمساوي اخو شرموطة بصفحتي 🙂\n\nنقطة وس...
108998  حتي يونس ابو عيطة ابو شباح مخزوق الي بتحمم مرة...
108999  كل واحد #حمساوي دخل صفحتي وهدد وغلط وشرمط لازم...

                                                     text
109995  ربنا خلق التفاصيل لصغيرة ورا هالاشيا المسافات ...
109996  لا الوقت ولا عمره راح يبقى لصالحنا فا بلاش منق...
109997  @inxnamo @Mogheershurrab بدري عليك يا حبيبي يا...
109998  @mazen3la2 باختصار انه الاعلام الزفت الاسرائيل...
109999                @mazen3la2 طبعا لا بس قرف يقرفهم :)

                                                     text
110995  كلمة " أغلب : نفس كلمة ' كلهم ' بس عشان محد يز...
110996  @mhamdabusherbi بس أوقات كتير بتكون هيك يا حمو...
110997                         إحنا إلي عملنا للخميس هيبة
110998  مش حلوة لو صارت حرب يحكوا تقاتلوا عشان شوية بل...
110999  فعلآ بتحسهم عايشيين في كوكب تاني https://t.co/...

                                                     text
111995  @Maryoom_T_M بتقتلني هاي البنت 😂😂😂😂\n\nميت مره...
111996  مع احترامي لليوفي بس مباراة ضد اتليتكو رح تكون...
111997  @R_alkarmii لا بتحسر ولا عبالي بكره بيجي غيرو ...
111998  @Maryoom_T_M @farahmohamad743 @MOHAMMEDASAAD_6...
111999  @Maryoom_T_M @MOHAMMEDASAAD_6 @farahmohamad743...

                                                     text
112995  @MohammedAssaf89 #محمد_عساف الله يطول بعمرها ا...
112996  @mousa_abdallah الله يسعده عساف ياارب 😍 ويطول ...
112997  @hishamsafadi1 @Layla__Reda @MohammedAssaf89 م...
112998  @Ne7naMagazine @MohammedAssaf89 الله يسعده عسا...
112999  @basil_hisham بتجنن الصورة يسعدوو عساف 😍😍 ويسع...

                                                     text
113995  @fatato2علي فكره انا بعذرك واضح  انك ما عندك ف...
113996  @fatato2 احترمي نفسك لغاية هنا و بس بلاش الكلا...
113997  @fatato2 عايزه المعبر يفتح علشان نشوف اهلنا ال...
113998  @fatato2 بس عموما انا لو يهوديه صهيونيه كان زم...
113999  @fatato2 اسفه علي الخطأ كنت فاكراك بنت ، عموما...

                                                     text
114995  @Mohammedaboselm يزم هو بحكي ع بياعين البمبرز ...
114996  متجيش تعملي حالك خايف ع مصلحتي وابو الفهم و تن...
114997    @Mosab21997 ههههههه يبني خليني معصب \nتفقسنيش 😑
114998        @NawrasRadwany مصممين تطلعوني شخص مش كويس 😑
114999  رابطة الناس الي صوتها زبالة و برده بتغني قدام ...

                                                     text
115995  @3boodsh95 @abdallhmuhaise هههههههههه لا محبيت...
115996  @AkkilaFahmi وانتا بالف خير يا ابو ايهاب ينعاد...
115997  @HazemNabeel ههههه شايف بالله ع وجه هالعيد مبلكنس
115998     @etisalat @khalilfouad بينفع كدا يا اتصالات ؟!
115999      @Mhamoud_Ahmed22 كلنا شايفين مش انتا لحالك 😂😂

                                                     text
116995  @RawanAbuAssaf @duaa_zone مهو لازم هيك لحتى يض...
116996  كيكة عملتها عشان بنتي جاية من السفر &lt;3 &lt;...
116997  @AyoOsh_11 ولا عمرهم رح يخلصوا \nلحد ما يتعرفو...
116998            @rdooan صحيح كلامك وصارت معي فعلا للاسف
116999  @mohamadaburas كان عند امي الله يرحمها منهم كت...

                                                     text
117995  عارفين لازم نستكنيص مع القرف و الخنقة و الملل ...
117996  @AhmedAsq و الغالي علينا غالي ولا عمره بيتنسى ...
117997              @AhmedJarad90 اللي مش عاجبو انفلووووو
117998                    يا مبعباصين ايوة يا معرصين ايوة
117999  انا مش عارفني انا كنت مني انا مش انا لدي ملامح...

                                                     text
118995  نفسي أفضى زي الناس الفاضيين وأزهق من القعدة في...
118996                     @osama_wafa7 يسعد هالمسا يا حب
118997        إرجعنا لديوان الجوع اللي بيجي في نص الليل .
118998  لسا في شباب بتحكي يا بطة ويا قمر و يا عسل ؟!😒\...
118999  كل إشي ما يكونش صح بيومي ويطلعلي مليون شغلة تن...

                                                     text
119995        لا أحد يهتم لأمرك إنت مجرد ربطة بقدونس. .😏✋
119996  في ناس عندهم ثقةة لدرجةة بيقولولي : الله يعين ...
119997  مفش أحلا من أيام الثمانينات ،ايام لما الواحد م...
119998                    ما هو أول انطباع أخذته عني ؟ 🙄✋
119999  زوجتي المستقبليه 😍\nانتي ربنا بيحبك❤️\nعارفه ل...

                                                     text
120995  بحب أشارك اختي اسلام بكل افكاري الغريبة و مخطط...
120996  و #لطيفة لما حكت \n\nشاايفة الدُّنيا حللوة في ...
120997  أسوأ حاجة لما الواحد يجي ع بالو اشي بآخر هاللي...
120998                 حاسة رح اموت ازا ما اكلته الليلة 😭
120999  يالله قديش صايرة أزعل وأتأثر بحالة أي شب بيصير...

                                                     text
121995  ميرسي منى كثير انبسطتنا وهيصنا واكيد يوم ما ان...
121996  امك ثم امك ثم امك ثم ابوك ....يارب يخليلي أياك...
121997  اليوم في السيارة السواق بقول شايف قديش نسوان ب...
121998  بلد العجايب ...الكهربا مضوية بالشوارع ...بس ال...
121999  عنجد راسي بتوجعني ...وايش كمان المصيبة الاكبر ...

                                                     text
122995  @25_mayar @Basant_Nabil @peacenislam @LianLuca...
122996  @25_mayar @Basant_Nabil @peacenislam @LianLuca...
122997  @Basant_Nabil @peacenislam @25_mayar @LianLuca...
122998  @25_mayar @Basant_Nabil @peacenislam @LianLuca...
122999  @peacenislam @25_mayar @Basant_Nabil @LianLuca...

                                                     text
123995  @Z5_AbuOmar الحظ بالعكس هاذي السنة مع الكتلان ...
123996  @rmzi_madrid @sergio4_ramoss4 ولا يهون الكلب م...
123997     @Barccelonii حتسووا ممر شرفي وانتوا بتضحكوا ..
123998  @InaniT0 انا بفهم شي ليش لعيبة مدريد مابتعترض ...
123999             @Nadjib__FCB استغرب تردوا على هالاشكال

                                                     text
124995  @tasneem_jamil @LFC @realmadriden @ZSCOfficial...
124996  @diaa_alfiqi مع الوقت يكتسب الخبرة لكن صراحة م...
124997  أحسنت التوقع 👍💙\nسيبنا يا عم الخبرة بتعلب دور ...
124998  @aseelsarsour الجولة الجاي برشلونة مع بلد الول...
124999  الريال لازم ينكد علينا هالسنة ما صدقنا وقلنا ع...

                                                     text
125995  @mohammedan96 هههههههههههه لا مش هتحس ب أي تغي...
125996         @mohammedan96 ههههههههههه العمر كلو يا رب😍
125997     @jehanii97 هوا ايش بطلع السيكا يا حوب هادا ؟ 😂
125998  @jehanii97 فظيييييع ما افخمووو هههههههه ، وينك...
125999  @jehanii97 بس هادا فخم للأمانة ، اذا في زيو با...

                                                     text
126995  جرح البدن بيروح مع الزمن٠٠ بس جرح الوطن ما بير...
126996  سوريا\nلما بغني إسمك بشوف صوتي غلي ٠٠ ايدي صار...
126997  @Bo3li1979 إن شاء الله نزور مقام السيده عن قري...
126998  من وقت ما كنا صغار ٠٠ صرعونا بإنو العرب أخوات ...
126999       @ana_alarabi @ahbeich71 شو رأيك نادي  يا جرب

                                                     text
127995  #يااااحرية ... \nماهر عليان عبد الله من منبج ق...
127996  #ياااحرية ... \nأحمد فاروق الهواري مواليد 1987...
127997  #يااااحرية ... \nأحمدعبدالسلام صوان من المعضمة...
127998  #يااااحرية .. \nمحمد طارق شاهين مواليد حمص 196...
127999  #يااحرية ... \nاحمد رفعات اللبابيدي مواليد درع...

                                                     text
128995  @sandyal232 شكلك مخربطة عم قلك لمن تحب مو لمن ...
128996                   @salam_F9 مدري ليش تذكرت هالمقطع
128997  @Houssam1966 لمعلوماتك انا بحب ياسر العظمة وبع...
128998      نص بلاوينا من هالحركة https://t.co/LO6e5qNMEk
128999  اللي كاتبة على صفحتها الخاص ممنوع بتعرفي انهم ...

                                                     text
129995  بحملة عيدية الماضية زارنا جاك سبارو "Johnny De...
129996  @iDallo_88 @ShazaOT العفا لسا ما التقيتو راح ك...
129997  @Homs_dream @ShazaOT @iDallo_88 😂😂😂😂😂😂😂 هي دي ...
129998  نزلنا من السيارة وهوي عم يطلع فيني ويبتسم  ..\...
129999             @elah_ataa الله يسلمك ويخلي أحبابك 🌸🙏🏻

                                                     text
130995  انا زلمة حبيت الكوفر يلي عمله اكثر من اغاني في...
130996  #آركيد لح تبلش من 19.09 باشتراك 5$ شهرياً من #آبل
130997                        الايباد الجديد بـ 330$ بس 😍
130998  من الحالات الرائعة يلي ساوتها #ساعة_آبل \nانه ...
130999  الساعة صارت بتقيس نسبة الضوصاء حولك \nلح يقدمو...

                                                     text
131995  @MTVLebanonNews يالطيف على أساس المسد سات شغله...
131996  @MohamedHnid ماعمري شفت هالإعلامي غير بالأيام ...
131997  سألت من أكترمن عشرة أيام سؤال\nحسين مرتضى كان ...
131998  @SaleemAldulimi وليش لسه بتعتقدبالأمم المتحده\...
131999  @pipo79081069 @seamo222 يجوز ولكن قريت عم تقول...

                                                     text
132995                     @j_alashkar يعني شو بدك تحكي?😏
132996  @AbuAbufadel هلا بالحبيب والمناضل والشريف بطرط...
132997       شي فزيع اللي عم بيسير بباغي  #جو_سوي_كرواسان
132998                        بخخخخخ سم #نكتة_عن_مي_شدياق
132999  أفعى نص حئيئة ونص بلاستيك أخخخخ #نكتة_عن_مي_شدياق

                                                     text
133995  أهلامايا منوره الله يرحم جوزك ويخليلك ولادك ht...
133996  ههههه والله لنخلي طريدهم لمالطا \nعاملين وزراء...
133997  #الغدا كبة وفتوش\n#بتحبو_هيك_اكل؟؟؟\nطيبي الكب...
133998  مين بيحب هيك اكلي\nكانت ستي الله يرحمها ويرحم ...
133999  التحلاي \n\n#قطايف بتحبوها؟؟ ❤😍\n\nوطبعا من جا...

                                                     text
134995  طيب كيف بجيب دولارات!؟! بدي تويت بوت والله ملي...
134996       😜️  كُل عامٍ وأنا بخير. وبالناقص من معايدتكم
134997                                  شو بحب أسم بلقيس.
134998  @jamilanadani آمين يارب وينعاد عليك بالصحة وال...
134999  @karazzkh وانتي بالف خير. وينعاد عليكي بالصحة ...

                                                     text
135995  @YasAlomar حقك والله\nدكتور ما بينمل من القعدة...
135996  @rosemar3ee شكله التدريب خلاك تكرهي المهنة عال...
135997  بعد ما كنت مبسوط أنو عم بشتغل بمشروع تخرجي مع ...
135998  يمكن من هون لحتى تروح عبريطانيا حكون استفدت من...
135999  @Samoxicillin والله سوتلي يا رجل🤦🏻‍♂️\nعقبال م...

                                                     text
136995  @sawsanarsheed @BasantHanie دخيل قلبك يا أحلى ...
136996               @hamodax شفلي الحلوين بطريقك زكاتك 😋
136997  @hamodax انا من زمان مو فارقة معي ..ياما نصحتك...
136998  @hamodax ههههههههه بربك مو حسيت بشعور حلو حتى ...
136999                      @hamodax الله يهدي الحال يارب

                                                     text
137995       @Jfeen_7 مايمديك تعدل الوضع الا تلاقي بالنصر
137996  @5BiPyZFD85Xy9hi @ALMRISEUL هذا رايح مكة ع شان...
137997  @5BiPyZFD85Xy9hi @ALMRISEUL ارجع اقلك اعصابك ي...
137998  @mr3loosh1 صافق حبوب لما دايخ وتجي تقول طرقهم ...
137999                 @Abudlim1 بكرة او بعده قريب ماتفرق

                                                     text
138995  @manno1112 @22mosalah هيدا مش لاعب طبيعي هيك غ...
138996     @Muhamed_Erdogan اللهم طهر صفوفنا من العنصريين
138997                 @Baraa_Abdul الله المستعان يا براء
138998   @LiverpoolAr يلي فاز عالسيتي مالازم يستصعب بورتو
138999   @rama__sh يالطيف شو سخيفة والحشا اسخف مناسبة 😂😂😂

                                                     text
139995  @AlkassabAmar وا أسفاه يا قمر على اللي خسرناه....
139996  @HowidaDaghesta1 @breayaoo شغلة بتوجع الراس\nخ...
139997  @lama_xx99 معناها ميزة اختبارية، بالتوفيق\nحلو...
139998  "إللي ما بكون حلمو بشر.. هو إنسان قادر على إنو...
139999  @TheSyrianTweet برا يعني بعد باب الدار ولا برا...

                                                     text
140995  فين آل سعود يشوفوا أعداءهم الحقيقيين . https:/...
140996  @Meh_shatha هيك مشروع ما بيمشي عنا\nكلو حكي فا...
140997  @S__aFi @Mohammed_Aloush طيب شو قلت له حتى عصب...
140998  @Obadaalshamii عيب عليكم تحطوا الاستاذ محمد عل...
140999  @S__aFi @Mohammed_Aloush بصراحة معه حق يعصب .....

                                                     text
141995  من الحاجات اللي م تنشرى بالـمال‚✨💶؟.. - الكرام...
141996  وش تقولون"جح,حبحب,بطيخ"🍉🌸؟.. - جبسي   http://t...
141997  الله يخلي لي هالمجهول الي يجي كل يوم 😔💕💜 - من ...
141998  اللي صاحي الحين وعنده مدرسه , وبيداوم جعل مكيف...
141999  ياخي هـ الايام تشك اذا احد قالك احبك ماتدري هو...

                                                     text
142995                @merzafatin وأنتي يا حيوانه شو رأيك
142996                     @abohoteh الله يحرق التنين سوا
142997  @mustefaebdi يا سيدي نحنا فرحانين بحيث ما يتم ...
142998       @alaaboyousef مو بعد أيام  على اعتقادي اليوم
142999  @AsadSouria ان شاء الله نقوم الصبح ولا نشوف ول...

                                                     text
143995  @nouramal28  ههههههههه باهي باهي تو نحيه وعد  ...
143996  والله لا ينسى اجر المحسنين \nامري لربي  انا نق...
143997  في #تونس فما لعبة اسمها " #شبيك_ما_تسألش" اللي...
143998             @Meehaa85  عيشك مهوتي  ربي يخليك ليا 😘
143999  @shahrinay8  حبيبتي ربي،  يسلمك عيشك ربي يخليك...

                                                     text
144995  خليها تبعتهولي 😒\nحد لاقي عرسان يا بهيمة https...
144996   با بلاش 😑 \nااااه قلبي 😲 https://t.co/tZKajLsPHr
144997  يا راجل دة في شاعر قطري كتب قصيدة يعبر عن رايه...
144998       دة ابن كلب ويعملها 😡 https://t.co/VrdtF1r5MH
144999  احسن 😁 ومن اعمالكم ما سلط عليكم 😜😜😜😜 https://t...

                                                     text
145995  🛑مفهمتش علاش برشا ناس يحبوا يفرضوا عليك رايهم ...
145996  عندي قناعة في الدنيا هاذي انو ما فما حد ينجم ي...
145997  عرض الزيارة حضرتلوا يمكن 8 مرات و مستعدا نزيد ...
145998  @salwa_tn هههههه علاش\n اني نموت عليها كل ماتج...
145999  @fatmaca4 المهم عجبك خاتر موش مغرومة برشا ب ال...

                                                     text
146995  @helajarraya_619 الصدى؟؟؟؟ هههه...تعرفيه موقع ...
146996  ياخي بربي فمة سلطة ونظام من أصلو باش اطيحوهم؟ ...
146997                  @maramoutloktn2 ماني الا شخص عادي
146998  سمعت شوية حمة الهمامي على الحوار. ظهرلي ماهوش ...
146999  بربي نوّرنا يا شيخ راشد: كيفاش مصطفى خذر لقى و...

                                                     text
147995  @Owisses هههههه ولايهمك وكرمالنا نزلو شي لعبة ...
147996                    @fakihn شكرا كلك زوء يعيشك 🌷❤😶☺
147997  @nour_yoyo20 لأن مصر حلوة فهي حبت تشاركنا لحظا...
147998  @NadineElRassi النجمة @nadinenjeim ملكة جمال ب...
147999  @Nanananito1 @NadineElRassi شكلي أنا اللي رح ت...

                                                     text
148995  مستحيل نصوت لواحد وراه حزب التحرير و ما يستعرف...
148996  نحب انبر على اصدقائي الي يحبو يدزو عبو على الي...
148997  سمير ديلو كل ما يتعدى في وسائل الاعلام يحسسني ...
148998  راهو يتحكك عليا \nيحبني نحكي عليه \nو يمشي يلع...
148999  العشر الاواخر للمترشحين للرئاسة كي يعملو حوصلة...

                                                     text
149995  @nawaf01984 @Soumamaya3 افتح كتاب التاريخ يا ج...
149996                 @WitnessTV2 مازالت ما شفتي شي خبيث
149997  مبروك لتونس اول خفارتين صنع تونسي 100 بالمئة م...
149998  "ولو اجتمعوا علي ان يضروك بشئ لن يضروك الا بشئ...
149999  @made_in_216 حسب كلامك نكسروا بلادنا. نحرقوها....

                                                     text
150995            @zazanaza1 يعيشك حبيبتي علي راسنا واللع
150996            @trrr85 احلي رجاء شكرا ياحبيبة التوانسة
150997  @latisol بنت بلادي الغالية ياىيت تدعمي نسيم ال...
150998  @IJnifen يااحلي زوجة لاحلي فنان ياريت تدعمي نس...
150999  @SueMoh7 ميهمكش فيهم حبيبتي احنا نحبوكم برشا و...

                                                     text
151995            @salwa_tn خرافات و تطير ، و التطير حرام
151996  @hakim1zed ما يقدر عليه كان ترامب او متاع كوري...
151997              @Wafa07943665 الله غالب ، امتحان صعيب
151998  @Wafa07943665 طبعا فرص تدارك ، نستناو اجوبة اخ...
151999  @kebchiza اللي عمل الصفقة و اللي دخلها من الدي...

                                                     text
152995  @khaberni ماظلى غير الحكومه تقول كلوا كعك بدل ...
152996               @khaberni زين اللي نطقوا نواب الغبره
152997  سوا ربينا سوا قضينا ليالينا \nمعقول الفراق يمح...
152998  @khaberni خليهم يشوف حال المواطن اللي صار حاله...
152999  @khaberni الحق مو عليه الحق اللي مخلينه ياخذ ر...

                                                     text
153995  @MohaAlRefai انا شفتهم الاثنين لايڤ .. هذاك كو...
153996  @omar_almanasreh على وزن ابو غوش في لعيبة اسطو...
153997  في فرق كبير بين "المتكلم" وبين "طويل اللسان" ....
153998  كثير ناس علقوا على موضوع الطبيبة اللي تم الاعت...
153999  @AmmarAMJ يا صديقي احنا قاعدين بنراقب قصة اثني...

                                                     text
154995       @_ISpain_ لا بتصحي زي الشاطره و بتروحي دوامك
154996  لما احاول ابين اني\nindependent strong woman 💪...
154997  @badrea_3 @Aloshart حمدلله اتوقع احساس الرسمه ...
154998              @roseattallah راح تشكريها فيما بعد 🙏🏽
154999  ازا طلب منك يشوفك من غير مكياج اطلبي منه تشوفي...

                                                     text
155995  @Sulaimanhwamil 😂 😂 😂 😂 😂 بدها إرادة بس، انا ك...
155996  @Heba_Abu_Diak احلى شي الرياضة بالصبح، يسعد مساكي
155997  @Asoolih 😂 😂 😂 😂 😂 رياضة الخوف من احلى الرياضا...
155998  @EQiblawi 😂 😂 😂 ابشري ولايهمك بس اشتريه انا با...
155999  @noOrabuQwiak اذا صرتي مليونيرة بتدعميني ولا ب...

                                                     text
156995  @dvVdmkzH0Zl9qGP الحرمه اللي تحط ثوم ع الملوخي...
156996                @khatib_areej تقول انها رحلة مدرسية
156997       @hamodca1 @Roula74884907 صب لها نص كاسه اقول
156998  @k7ybnd99 @alqubilat_hkj1 خذ العرص عامل مشترك ...
156999  @Alaa_Alhmoud العفو والله\nبس الحين كيف ودي ام...

                                                     text
157995     @safa2smadi العتب مش عليكي..العتب على صاحبتك 😒
157996  انا ما بقلك اذا في اغنية بسأل وجهة نظرك احنا و...
157997  @safa2smadi @TasnemSmadi كل وحدة تصير طلعة شكل ☺️
157998           @Ranyaa_ @TasnemSmadi 😂😂😂 و هسا عم اتعذب
157999  بتفكري تتحجبي هالسنه ؟ — الفكرة دايما موجودة ب...

                                                     text
158995  @IslamAlhmoud وانا والله نفس الحاله مبين كله ن...
158996  @IslamAlhmoud شكله خرررافي 😍انا بحكي نبدأ و نت...
158997            @JeehanAl احنا ٣٣ بنت و شب jfdaتخيلي😂😂😂
158998  @RayaSeifan @Mona_09__ ههههههههههههههههههههههه...
158999  @Raghadyahya5 حبيبتي رغوده ان شاءلله ببتعوضي ع...

                                                     text
159995  و بيذكّرني فيك لون شبابيك ، \nبس ما بينسّيني ش...
159996             يا سلاااااام أخبار حلوة طول اليوم.😃😃😃😃
159997                      انا نعسانه من ال ٢٠١١ تقريباً
159998                   ما رَح ترجع.. بعرف إنّن غيّروك..
159999       اسند نفسك بنفسك ، كلهم حيطان مايله يا صديقي.

                                                     text
160995  @evamaaitah في بلادي.. دائما  عبارة \nأنت عارف...
160996  مش صارت هالعادة  باردة \nلو أنا المسؤول بشجعه ...
160997                     @jo_8_ry الله يعيين يا قلبي 😍💛
160998  لحد الآن ما بعرف كيف في ناس ما بتصلي، يعني جد ...
160999  @ta_1m @nooooooooor_16 @r_jordan_j هي حاليا ما...

                                                     text
161995                 حرقت المفتول و خايفة اعترف لإمي 🙄💔
161996  @MosaubZyd صح بس في لقطة من اللقطات بنحط مرقة ...
161997  رسالتي ل 2018 قبل ما تخلص؟!\n "ايه يا شيخه\nاي...
161998  @machinery1994 لا يوجد app 🙄.. حسب ما بعرف انل...
161999  @machinery1994 هههههه لا حسب ما بتذكر في وحدة ...

                                                     text
162995                  @besootalal يارب كرامه للنبي محمد
162996  @besootalal الاولى ضيعوها عشان الثانية \nالثان...
162997     @IstraightI @Fairouzna الله يرزقنا ونجتمع صدفة
162998  @besootalal في أشياء بسيطه تستاهل نحب الحياة ف...
162999  @3s_87 مجرد جاري الكتابه من شخص تحبه شعور روعه...

                                                     text
163995                                بالي ضايق ضيق كايد😔
163996              نفسي أعيش لحالي ببلد ما بعرف فيو حدى😊
163997      @3ajramista بصير أحسدها😅\nجد نيالها🙈🙊\nأبدعت👍
163998  @Nawafleh91 ههههههههه نوم الهنا بس جد هاي النو...
163999                   عأساس الدوا بنيم وينو هاد النوم😣

                                                     text
164995  -المناقشة بعد اسبوعين 🙆\n-اه يعني كمان 14 يوم ...
164996   وجداً جداً جداً للأبد 💜💜 https://t.co/yZEDTX70JR
164997  @nouf_alkhraisha @EmanKAlhammad1\nالثقة هاليوم...
164998  @EmanKAlhammad1 تخيلي نخسر صوت يا شيخة... احنا...
164999  @EmanKAlhammad1 له له عيب هالحكي انتي عارفة قد...

                                                     text
165995  @allawnehyazan هو احنا طايلين النيل الي بحد دا...
165996  @al_naw الله يبارك فيكي و يسلمك بس ليسا بكير, ...
165997  @nagh_amsh هم 120 يوم دراسة و 70 يوم امتحانات ...
165998  @ZooZGooV حط صورتي انا وياك و امورك ماشية حبيب...
165999                      الوضع مش سهل بتاتا البتة .😳😡😢

                                                     text
166995  عند اهلي لازم اي اشي يخرب بالبيت اكون بعرف اصلحه😑
166996  ليش كل حياتنا استعجال؛ بنصحى مستعجلين بنروح عا...
166997  الصداقات اللي ما بتتأثر بسبب قلة المحادثة، نعم...
166998  @naji_931 @mokh199 هو صحيح ممكن يكون عمل جهد ....
166999  عن كمية الأنطفاء الي بتيجيك بعد ما تكون متحمس ...

                                                     text
167995  @alnaayaafaa انتي سمسار من الآخر هههههههههه  مكسب
167996  @ream24445888 @llllltooof الانفتاح عنا بالأردن...
167997        @1947_asg إنشاء آلله يارب ماعاد نشوفه يشارك
167998  يخوان اش صار باصابه لافي وأصابه اوبيلا يشاركون...
167999      @forcabarca_ar اعطني لينك بتاع القناه الرسميه

                                                     text
168995  @almunifi74 اولاد الخمس دقايق مالهم الا التطبي...
168996                   @almunifi74 عساهم من الحال وازود
168997  @almunifi74 خله يزبط حواجبه وشفايفه للولي السف...
168998  @KbESq ههههههههههههههههههههههههههههههههههههههه...
168999    @KbESq المشكله انه هرب معهم عامل نفسه مايعرف شي

                                                     text
169995  لا إشتقت لك ناديت من قلب : ياربّ\nربي هو اللي ...
169996  علم الي يحسب انه من الروس الكبآر \nالعلوم المر...
169997  وقتي اللي حطني بين نار وبين غار\nأستدار وضربت ...
169998  علم اللي يحسب انه من الروس الكبار\nالعلوم مرقع...
169999  والحر حراسه من الخافق إحساس ** نفس عزيزه ماتعر...

                                                     text
170995  @mohammedShamekh @MarahGHaraibeh اذا هيكك ممكن...
170996  @MarahGHaraibeh @mohammedShamekh هاي شطارة مش ...
170997  شفتهم بمادة او ثنتين بس \nبعدها فقدتهم وضيعتهم...
170998  @fareedah1997 اذا هيك معناتو ان شاء الله ي ررب 😅🙏
170999  الله يرزقني هيكك فرحةة 😂🙏💙 https://t.co/66ukkR...

                                                     text
171995  والاهم من ده كله اوعى تقول كلوب ما يعرفش يدرب ...
171996  @Nour_Huneity97 يعني سحلية عدت من رقبتك ولا صح...
171997   @Nour_Huneity97 طيب لا توكليش بيض بتزبط امورك 👌🏻
171998  @Nour_Huneity97 بعرفش هيك عادل امام كان يحكي ب...
171999  @Nour_Huneity97 عاد البردقان بفهم عالطاير بس ي...

                                                     text
172995  أضفت فيديو إلى قائمة تشغيل @YouTube على https:...
172996  موعود فيها صار الي مدة ولما تلاقت يدها بيدي .....
172997  ومفيش غيرك ع البال \nhttps://t.co/nIbB1gZmfP h...
172998  متحلمينيش جاي على حصان .. عدانا وفات زمن الفرس...
172999  قد كل الليالي دية واكثر شوية .. \nhttps://t.co...

                                                     text
173995  @ghadeerita هو اريح للراس اريح بكثير.. \nبس لو...
173996    خلي يمشي متنا السنه 😑😑😑 https://t.co/HRQvGlhncF
173997                   ليش البنات بحبو لون الزهر 🤔👠👛👝👗🍑
173998                         يوسف سيف باكل الراس اكل 😑🐸
173999      شفت! غيرني هواك 🙊❤\nوخلاني ارشح ويلتعن عرظي 😑

                                                     text
174995         تستاااهل قلبي و دقته 😍\nبوسات انطيگ مربع😚💜
174996   احكولي شي حلوو 💜\n#صراحة https://t.co/sPKEC838NY
174997  كلام يرفع من معنويتي شوي💜\nنفسيتي 0%😔\n#صراحة ...
174998  القاعدة بتحكي:\nالي بيحكيلك انا ما بكره شي بال...
174999  محلااا جوووو الهاشميةة😍\nومطرهاااااا وريحة ترا...

                                                     text
175995  @mohammedawaad والله بالنسبة لي اهم صفقة هي حا...
175996  @alsaad1984 @A_AlHameedi والله ثم والله مافي ا...
175997  @khaberni طيب ليش كنتو مبسوطين باتفاقية النفط ...
175998  @AlShsu بس ياسلمان مافي دخان من غير نار والله ...
175999          جوانكا مالو اي دور بالملعب\n#النصر_الشباب

                                                     text
176995  @A_Gafes مرة إشتريت كوابل أنكر من أمازون البري...
176996  @SalahGHamed أنا بشوف التصميم من ورا كلو غير م...
176997  @RoyaNews على أساس بدكم تطلعو علما ذرة روحو عا...
176998                   @RoyaNews حقهم إنتو أصلا مستفزين
176999  @RoyaNews انتو عاملين زي سواريز بس لمسكم صار ع...

                                                     text
177995                    @Aburob_Photo مسكر على حالو شوي
177996                     @Albsimi يبي يلفت نظر بالغصب 😂
177997  الي فترة مابنتقد أمور سلبية ببعض الناس لان عال...
177998            @_heba2018 ليش انتي عايشة عال 3G ؟!!! 😂
177999                           بفكر أحط دعايات بصفحتي 😜

                                                     text
178995  بس "يكذب" المهم يخبرها بأنه عايش ! حتى نهاية  ...
178996  #حصار_طبربور مسكرين اشارة طبربور عشان الباص ال...
178997  @KathemAmin واطيب  التمنيات لك بالشفاء العاجل ...
178998  @hile_sh بنباع الشعر سيدي وبتبرعوا بسعره لمرضى...
178999  @alzoubi_ahmed احنا مش رح نشربه شرب احنا رح نت...

                                                     text
179995  @edengreed 😨😨لساتني قاعده بفكر اقصه وهيني بتفر...
179996  @edengreed بدي تغير قصه حركات غره او تشفير مو ...
179997  بكره الصيف\nوالله صيفنا مو صيف صيفنا جهنم http...
179998  بتكون كافي خيرك وشرك وماشي جنب الحيط\nما بتعرف...
179999  بيوم كان عندها عملية وكثيرخايفه منها ولاني وحي...

                                                     text
180995                      احس كل الناس سافرت الا انا 🥺💔
180996             @IDawood123 من قالك بجده انا 🤦🏻‍♀️😂😂😂😂
180997               @murad112008 الحمد لله طلعت مو لوحدي
180998  @hilal5590 ياعمري والله اتشرف فيكم وانتو بعد ت...
180999   @alosimi94 @we_daa18 من متى والله ماقلتي يالغشاش

                                                     text
181995                     @Sweel29 ها واحد آخر زدني حداك
181996  @ProfiSalim اخي انا والله لحد الان مازلت مصدوم...
181997  @tkhrbi9a_s لاء مغبروش رآهم كاينين وتينبحو من ...
181998  @ProfiSalim مطلع لي والو 🤣😂  واضح داير ليه بلو...
181999  @AbdelazizElkas3 والله حتى عندك مكدبتيش نزيدك ...

                                                     text
182995  @Dr_Fizazi @BrotherRasheed عطيتي لبخوشة اكثر م...
182996  @Lemriguel @sofiaghannam أودي شفت ما كثر: بناد...
182997  "@Mhmd__9: عندهم اخونجية  !!!\n\n#هونغ_كونغ ht...
182998  بغيتو تعرفوا مستجدات البلاد؟  @map_maroc  ماخد...
182999  @ITS_Meee_MARIO المهم الزاهيدي غادي يزيد يطول ...

                                                     text
183995       @ro9ayadagadir الحمد لله اتاسنو موجوده دايما
183996  @wrtyippp @OtOtmani @NajouaRjf @ShaymehElissia...
183997  @ahlam_alshamsi مدام احلام انا نحبك بزاف انا م...
183998  @Ahlam_A أحلام أموت و أعرف مالك و مال سلمى كل ...
183999  @SalmaRach سلمى البارح أبدعتي بغناكي و حضورك و...

                                                     text
184995  فلافل فلافل بدون فلوس من بقدنوس 😂😂😂😂  #MBCTopChef
184996  @samiapease هههههه 😅 جايبينها بالمزيان و لكن ن...
184997  @samiapease ماعرفتك و انتي بالكسوة البيضة و ال...
184998                   #ثناييات_مغربيه\nرمانة و برطال 😁
184999  #كلمة_بغيتي_ايهاب_يقولها_لك @Ihab_Amir \n#Ihab...

                                                     text
185995  @c7FqwcIgvRj048I @EiadAkk @DjokerNole ماتهمني ...
185996  @c7FqwcIgvRj048I @EiadAkk @DjokerNole فاضية ان...
185997  @hadad_fa 😂😂😂😂ايه الجيب كيقولك شدي الركنة مكاي...
185998  @Abdlgha89189936 وييييه المشكل مشكل فواحد الشك...
185999  @aziz_hinni ايوا جي سطاسيوني حدا اختك ونشرو وا...

                                                     text
186995  @rmona11 تونس والدول الافريقية متخلفة؟! مين ان...
186996  @Al_alliaa @1415Alamal @rgb_seif @emirates وان...
186997  اني اخرجت ناس من حياتي كانوا سبب ازعاج وهم وغم...
186998  تعويم الدرهم فرصة للشباب للي خدامين في الويب ا...
186999         الوادي يعود لمجراه الأصلي مهما طال الزمن .

                                                     text
187995  @juan01116 لاحظت انهم جهلو عليه بزاف بعد هاد ا...
187996  @juan01116 واييه يلا بقات هكا ممكن طير ويرجع م...
187997  @10Maghrebiya باينين التزفاتيين هههه فين ما شا...
187998  @ayabeela19 يعني انتم شايفين هالموصفات لي تكلم...
187999  @foulamarocaine ومن سوهابية يعني هاد الفانز  ك...

                                                     text
188995  @MohammedAraichi والو غير مكاين لاش يكونو عندي...
188996           @MuNouha هههههههه ...و بالنسبة ليك نتي ؟
188997                 @MuNouha بصراحة ما شفتش الردود...🌹
188998           @Siiimohamed7 وعلاش ماشي الاسرة اولا ؟!!
188999  @Siiimohamed7 😞 نقطة ممكن نختلفو فيها \nماشي ب...

                                                     text
189995  @sekarwac @AbdellatifIrak1 كولشي ولا كيهلوس با...
189996  آودي يكون لي بغا يكون وراء هاد المقاطعه راها ع...
189997  @Elotmanisaad هاد "خالص"أصلا فيها إن ونتا مغرب...
189998  الإعتذار وخا ماقابلينوش ولكن مني حيدتي الكرافا...
189999  @K7al_L3afta ها علاش المزكيطي كيعجبني كيجلس تي...

                                                     text
190995    @AmazonSwarriorS و شنو المعنى نورينا الله ينورك
190996  بنادم عيا من الطريق ديال كازا و حطو طموبلات و ...
190997  بغيت جميع المقاطعين يبانو في هذا المنشور جيم و...
190998  طاليس كايقرا كتاب بالمقلوب و نظارات سوداء...#c...
190999  تخايل معايا مايحضر تواحد لموازين ، وعندها سيتس...

                                                     text
191995  @Ysf_alawneh @albanderiS البندري الشخص ذَا الي...
191996  @asma_alrajeh مرحبا ام صالح ياهلا والله بهلنا ...
191997  @Farida_Murshed @nourakh7_ الله يجزاك خير يافر...
191998  @Dr_A_Lawyer @Judge_a يخوي لاتزعل علي طال عمرك...
191999    @asseedan صباح الخير ابو بندر وش مسهرك طال عمرك

                                                     text
192995  اسوء نكبه ممكن تواجهك يوم تأكل وتقول للي عندك ...
192996  بعض الشباب مستقعد للبنات اول ماترسل مجهز ضحكه ...
192997  ترا راحت موضة البنت اللي تسكر باب السيارة بقوه...
192998  ايش فطرتي حبيبتي ؟\n\nالبنت : سلتة 😆 \n\nوهي م...
192999  انا لو ادخل سحب جوائز لحالي؟\n\n يفوز الصندوق ...

                                                     text
193995  الفرق ان العالمي بالكاش يعني بخشم الريال😍 ومال...
193996               @AlNassrFC بيض الله وجهه وماقصر ❤️❤️
193997        @Mehlisy يارب يارب يارب يارب ، الله كريم 😭😭
193998  @azizhadlaq2010 @saudiFF اذا على الامانه فيه ب...
193999  ماشاءالله تبارك الله عليه ، اهنييييه والله ماو...

                                                     text
194995  والله أحبه حـب مانيـب مخفيـه ،،\nحبٍ سكن باقصى...
194996  حبايبي متابعيني جزاكم الله عني كل خير ،،شاكرة ...
194997  @omrakan1619 حبيبتي وعمري جزاك الله خير والله ...
194998  للجميع ،،\nالله يصبحكم بكل ماتحبوا وتتمنوا يارب 🌱
194999                      بكيفه ،،لو كيفه لغيرنا بيوديه

                                                     text
195995  ردد معي  ثلاث مرات \nسبحان الله وبحمده عدد خلق...
195996  " ركعتا الفجر خير من الدنيا ومافيها " المقصود ...
195997  يارب نسمع خبر الإعفاء  #اعفونا_من_قرض_بنك_التسليف
195998  سنة الفجر: ركعتين قبل الفجر نقراء  فيهم سورتين...
195999  لا تنسون سُنة الفجر و هي ركعتين قبل الفريضة وق...

                                                     text
196995  @lulualfozan89 جميلةً مرة فيها جاذبيه عجيبه \n...
196996                 @haya131212 عيونك الحلوة و الله 😍🥰
196997  @roseslily65 انتي جمالك شامي تركي لمى .\nملامح...
196998  @retirement_m 😂😂😂\nشكرًا شكرًا اهم شي الخدود \...
196999           @i6aliyah فنجانً قهوةً و اغنيةً رايقهً 💗

                                                     text
197995                   @iib7h بيتشمتون الحين حبايب سامي
197996  @khhk223 @Law_tunv نايف ناشي من افضل الدكاترة ...
197997                  احساس : الفارق بكرة بيصير نقطة 🙃😌
197998  @_xrasha اووه زمان عن الهياط واحشني عشان كذا\n...
197999  @14Morooo قد جربت وفيه اللي صاب وفيه اللي خاب ...

                                                     text
198995  وين احجز #قبرص بكره رايح على صياح ذا الرخمه😂😂😂...
198996  قربت تتيسر ان شاءالله مايتعشى الا مع امه الليل...
198997                   @_haaajs_ باذن الله تعالى بتتيسر
198998  @Ahmdev @Bdah2424 اولا المبلغ موب لي ثانيا الم...
198999  @Ahmdev @Bdah2424 اتمنى ماتمسح منشنك والدولة ه...

                                                     text
199995             @al_dogrie ايو الله صادق وانا وش دخلني
199996  رقت برج ايفل واشتبك من عليه النود\nورحب  لها ا...
199997        انتهينا من الغمازات !!! \n\nشوفوا لنا غيرها
199998  ياليت التجارب تنحفظ صم قبل الشيب\nعلشان من شيّ...
199999              @Bdoor_sss ديرة بدل ديره ودار بدل دار

                                                     text
200995  #مانع_بن_شلحاط\n\nيالربع خلوه يستانس وينبسط ،،...
200996  #اغنيه_علي_البال\n\nاغنية ( خير ان شاء الله ) ...
200997  #يبرد_الحب_اذا\n\nالحب يبرد اذا ماصار فيه اهتم...
200998  @ben_aon عمار يادار الوفا والجود \nيااوفى الري...
200999  @sbinbtlaa ياسيدي لو يديني صار فيها ( رجفه )\n...

                                                     text
201995  @italotibi @MOISaudiArabia لما انتهاء المقطع ب...
201996  @dr_khalidalsaud  سلام وش علم المقطع ذا 😢😢😢😢😢 ...
201997  اي واحد ينطنط ومسوى ذكى وينتقد الدوله  ترا تنس...
201998  امراء ووزراء طارو الجرابيع ذي امرها هين باذن ا...
201999  @KSAMOFA فيه ناس ماتعرف انقلش انتم تكتبون للعا...

                                                     text
202995  @wm866 فاتن.       سحر.       إيمان.    ياسمين...
202996  @fSG7kMtkVcRzrzo @i6__80 غريبه نسيتي منطقتكم ا...
202997  @BGbSpBKDkAMNX3c اللي يفوز بها يارب يعطي الثان...
202998                  @Gfsooly وش هذا اعلان والا ايه ??
202999              @Gfsooly هههههه وراكم وراكم عسيري 😂😂😂

                                                     text
203995  @sak_fsad_wld_ @k_alsh3laan @AlnassrFans @faha...
203996  @ase50800 @AlNassrFC هذا القريق عظيم شريف بطول...
203997  @alsmariABD @sport24_tv هههههههههههههههههههههه...
203998  @alsmariABD بما إنك هيلالي ردد العالمية صعبة ق...
203999  @ase50800 انا اقصد النصاف السيدات اما السيدات ...

                                                     text
204995  @naomizzm  حسبي الله المفروض اخوانها يضربونه و...
204996  @4keek @asftalhzm49  يارب يجون يسرقون هالمبلغ ...
204997  @walaa3210 😂😂😂😂😂😂😂😂😂 واخرتها تاخذ ولد عمها ومه...
204998  @fofo_mahmadl مره واضح إنكم منتو محتاجاته http...
204999  #ساحره_الرياض \nوش بتستفيد يوم تستر على وحدة ت...

                                                     text
205995  تدري وش اكثر شي ودي اسويه\nاطوي كفوفي خلف ظهرك...
205996  العيون احلى من عيون المها \nشافها قلبي وصفق وا...
205997  ما تفيد القلب وصفات الطبيب\nلا امتلى قلبكً من ...
205998  ملعقة عسل واحدة يومياً \n كفيلة بان تبعدك عن ا...
205999        @Fjralsho8 @bumedarbi طيب ع اليمين وش موجود

                                                     text
206995       @shmrinnn @U__jod الله يجزاك ووالديك الجنه🌹💜
206996  @lala124123 آمييين يارب العالمين وجميع ابناء ا...
206997  @ArabiaWeatherSA اي والله عندنا زاد الغبار وال...
206998  @malmahmoud9 @AjelNews24 انقلبت فوقك تريله وزن...
206999  @AHMADALJEHANI1 @saudi_sniper1 صحيحه ونص وتعشى...

                                                     text
207995  @ahjh_althani هو برضه اللي يسافر ويتبكبك في كل...
207996                   @MRamsees10 اي معلومات انا مستعد
207997  @faisel_900 @SaudiNews50 ياليتك تصير مثله والا...
207998  @mnorelax @SaudiNews50 يعني اللي يسوون البزاري...
207999  @AJABreaking @AJArabic ماكرون هذا مهوي النصاب ...

                                                     text
208995  بان الفراق وحان توديع الاحباب\nوالدمعه اللى بي...
208996  الليل موحش اااه ومن ليل الحزن\nاليوم دور الحول...
208997  فيني ضيقةٍ في ضمير النفس مخفيه\nتعود القلب على...
208998  واللي يبي قربك وبالفعل شاريك\nيحرك عشانك كل اخ...
208999  معاد لي قلب متصبر ومتماسك\nياللى جرحت المشاعر ...

                                                     text
209995  @a_albander الله يشافيه ويطول بعمره.\nالمرض تط...
209996  @abuwesam_1555 @k_s_a_20_10 الدين واحد وش اللي...
209997                  @GMCarabia ينقلك الى عالم الورش👌🏻
209998  #سند_محمد_بن_سلمان\nصاحب الصورة يقول طاح مني ش...
209999                 #البنزين\nتعرفون معنى شويه شويه 😂😂

                                               text
210995  @rassamaldhoo \n\nكلك ذوق تسلم اخوي عبدالله
210996                   @rfmhn تسلم اخوي فهد مشكور
210997               @ArtNader مشكور اخوي نادر تسلم
210998      @asmulhem \nالله يبارك فيك وتنورنا اكيد
210999     @SeddeeqAK \nالله يبارك فيك مشكور يافنان

                                                     text
211995  فيصل بن تركي يقلل من فريق الإتحاد بعد تسجيله ا...
211996             اذا ابدع سالم أختفى نواف والعكس صحيح !
211997  ديمتري باييه حرام يكون في نادي زي ويستهام .. أ...
211998  بياتوف حارس أوكرانيا مو طبيعي أفضل اللاعبين في...
211999  يا هلا باللي لفاني يا هلا به 💙OS\n#الهلال http...

                                                     text
212995  صاير عندي احترام رائع لذائقة الطرف الآخر،  لدر...
212996                @mai_allafe يازين ريم ويازين أمها❤️
212997                       فايزة قطر علينا، وش تتوقعون؟
212998             وارجع اقول قطر فايزة علينا وش تتوقعون؟
212999  مدري وش اقول والله لكن ياحسافة بس\n #السعودية_...

                                                     text
213995  ليه أحس إني وأنا اشوفك حزين .. \n\nوقلبي الليل...
213996  ساري وأصوِّت لَك أبيك ..\nالنَّظره في عيوني تب...
213997  احبك لو تحب غيري .. \nوتنساني وتبقى بعيد ..\nع...
213998  همس النديم اللي يـعاتب نديمــــه....\nصوت المط...
213999  وصحى الليل مظنونك أغاني\nقصّت جناح الثواني غيب...

                                                     text
214995     @fs20142 @abobasilghamdi يقصد الاهلي واضح جداً
214996  وشنقول يعني \nواضحه بصراحه جداً 🤣😂\n\n https:/...
214997  @Y20 الله يبارك بأيامك وعمرك\nعقبال ما نشوفك ا...
214998  فلم هندي 😂🤣\n\n https://t.co/GScU6ElWX3\n\n #و...
214999  يا غايب عني ترى للبطا لوم \n\nلا شافتك عيني ول...

                                                     text
215995               @10azHassan الله يسمع منك يابو صبحان
215996  #صباحات_الهلال\nصباحكم سعادة وفوز ان شالله ياز...
215997  @abofahad1368m @MnbrAlhilal @a_alhanyan ماشي،،...
215998  #الهلال_الاهلي\nراح تندمون يالاعبي الهلال على ...
215999             #الهلال_الاهلي\nاكبر غلط خروج كاريلو؟؟

                                                     text
216995  @ahmed_alrshedy @brodcast_al الذئب لو يشكي شكا...
216996  احس الارض مقهوره على نجل الفخر صدام ..\nقهر يش...
216997         @facts444 @boun__ty المخ وين التدليك معه ؟
216998  @Kaled10003 1:شيعة، يتدارسون بما بينهم يا حجي ...
216999  @Kaled10003 الله وأكبر الشيعة لما تشوف هذي الص...

                                                     text
217995  @saudqn كل فروعهم وأخذت اليوم منهم كيكة الزعفر...
217996  @aroodh2030 لا تقربكم خايسة خاصة كيكة الزعفران...
217997  @aziz_alomar @alkhobarcafe @AlsharqiyaCafe @da...
217998  @aziz_alomar @alkhobarcafe @AlsharqiyaCafe @da...
217999  @AlJabr_Laundry أوسخ مغاسل ثاني مرك يوسخون ملا...

                                                     text
218995                           ياذا المعالي عليك معتمدي
218996  ماعمر التواضع نقص قيمه انسان \nوماعمر التكبر ا...
218997  @aimn_sophi حق ايش يجيب لك هديه وانت ماتعرفه\n...
218998  @omarbaoom1 ايوه صح السوال وماتملكها ايوه هههه...
218999  @Hananalwadee هذا الاب نفسه يشتيله ضرب \nبدل م...

                                                     text
219995  اليد ذي ماتعتصر لك بوسها\nهذا المثل خلى القباي...
219996  يا عفاشيين الطايرة اللي مليان زلط كانت باتكفي ...
219997                         القرش يلعب بشقران الشعر..!
219998  شدي يا دروب الوجع ... عيشي صار مثلي وجيع\nلا ه...
219999  @Aa23_0 محويتي \nحسستني ان ذي بيستخدموا تويتر ...

                                                     text
220995  بنتيري مش راضي يسبر \n\nھَھٍھَھٍھَھهه󾌴󾌴󾌴󾌴ھَھٍھ...
220996  اللي مستعجل للحور العين ينزل #تعز 󾌩 https://t....
220997  بقضي ديوني واللي تبقى ثلثين لدعم المقاومه بتعز...
220998         تم يارب يكون حظي  #ايفون7_هديه_مجمع_النزهه
220999  #اطردو_اليمنيين_من_السعوديهلا قلت تكفي طشو شما...

                                                     text
221995  @hamedalcont ورد =شوك\nملائكه=شياطين \nevet له...
221996                           @HeeeMv اهم شي حبك لنفسك
221997  @Samakuwait00 بتتعبين وانتى تشرحين هالامور وال...
221998  اذا صار مايهمني الشخص معاد يكون عندي فضول اعرف...
221999  الصداقه مش بها الامور 🤨 ماتفرق https://t.co/HL...

                                                     text
222995       @Iivil7 ماشاء الله عليها مبددددعه ربي يوفقها
222996             @HeeeMv قسم وقتك وحلو كثير جيد جداً 👏🏻
222997  ١-عاجبك اسمك؟ يب\n٢-تحس انك مغرور؟ يقولو مع ان...
222998  @2Da9A39A8feRLqD جمال 😍 هالمشاريع مستحيل نشوف ...
222999  @Aimen_Df الحمدلله وكون قوي لا تحط هالافكار براسك

                                                     text
223995  اللي أحتفلو ب\n#اليوم_العالمي_للعيون_الحلوه\nت...
223996  وانا اشوف لو ترجع لها تركيا وتكمل تقدم نشرات ا...
223997                        الاداء مش حلو خالص زي الزفت
223998  @sana_jad \nسمعت الاغنيه وغيرت القناة ما كملت ...
223999  @WalaaMo91505375 \nانا كرهتها بسبب التطبيل الز...

                                                     text
224995  ودي برساله طوييييييله يكون فيها شي يسعد خاطري ...
224996  صرت عادي اشوف اشياء تقهرني واسكت, لان ادري لو ...
224997                        @H2n1i يب يب.. انا صاحي لهم
224998          @mll6800 أي والله هذا اللي يقهرك للامانه.
224999  @2lini_ الله يسعدك ويفك ضيقتك.. ويعينك ويبدل ا...

                                                     text
225995  @MISS_3DN ههههههههههههههههههه بيطيروا  بالشاصا...
225996               @Alkhaldi990990 شكل سلمان الي بينحاش
225997  في اليمن مجهود حربي \nوفي السعودية رسوم الاجنب...
225998  @ShbaabYemen قصدكم أن سلمان بينتهي من أليمن وي...
225999  @alghorbani_ip5 @PWn9Si7ErNeTbkf والله ماامراض...

                                                     text
226995  @rabeea_201 \nاميره شوفي الحوثيين طيبين في كل ...
226996      @jerrymahers @gapri111 \nجيري ماهر وتوم وجيري
226997  @bntzienb \nيابت العسال انتي عسل وكلامك عسل وت...
226998  @DrDimashqiah \nد دمشقيه ملعون ابوها جامعه جاب...
226999  @Asaad__alsharif \nقمة الرومنسية يا اسعد الله ...

                                                     text
227995  @AliNajim اي والله غبار كثير الله يكون بعون ال...
227996                     امره الى الله من فرق بين قلبين
227997           @AliNajim صباح الكابتشينو بالرغوه الحلوه
227998  @FahadAlAliwa ههههههههههههههههههههههههههههههاي...
227999  @RM4Arab رونالدو كم اتمنى الروجوع الى مستواك ا...

                                                     text
228995  @Hadli_Manel كان الاداء روعة خاصة ان الفرقة جز...
228996  @fleurbonoise1 😀😅😱مزية منعنا باعجوبة كون زادو ...
228997  @Pamela_ElKik وانتي كبرتي في عيونا وقلوبنا مرح...
228998  @NinaTrSor نقدر نسقسيك \nانتي جزائرية لان تلفت...
228999  @NinaTrSor 😂😂😂😂 تعلمتي بزاف انا قلت ياعايشة تم...

                                                     text
229995  @chouchadz @MaiElgharbaawy @X_NISOU @AfafMadri...
229996  @MaiElgharbaawy @chouchadz @X_NISOU @AfafMadri...
229997  @MaiElgharbaawy @chouchadz @X_NISOU @AfafMadri...
229998  @MaiElgharbaawy @chouchadz @X_NISOU @AfafMadri...
229999  @012869945mmmmm1 @AwaTefDz23 @chouchadz @AfafM...

                                                     text
230995  @dz_twin صح لكن كاين لي مش حاب يتقبل انك انسان...
230996  @AntarBibeche3 و الله بعضهم لو مش متابعتهم من ...
230997  @bentbarika @saharfars صح ، لكن انا شخصيا هاذ ...
230998            @AmineAmroune2 تسلم يا جريئ يا رومنسي 😂
230999  @MouhZahir يعني يربو ولادهم على ان الرجولة تتم...

                                                     text
231995      @night82loord جرب التصغير و انت تقتنع ههههههه
231996  @night82loord يسعد صباحك، انت ما رحت أنا قصدت ...
231997   @night82loord يا عيني عليه الحب عامل عمايلو عليه
231998  @7byby_ هههههههههه خليهم بوحدة لا تزيدي تفتحي ...
231999  @night82loord ههههه مو عامل شي بس انتقام مو اك...

                                                     text
232995  @AHADI4 اذا ما لقينا دواء للغباء سيبقى لدينا م...
232996          دخل الي راح يسجل هدف الفوز الغالييييييييي
232997                @a7mad_mas يمكن لازانو بتاع المكسيك
232998  @a7mad_mas ضيف لها 9 مروغات ناجحة ، 8 عرضيات ،...
232999  @memomadridesta لو تاهلوا بهذا المستوى راح يكو...

                                                     text
233995  @Ania27El جزائريه وبربرية وامازيغية حرة واصلي ...
233996  @Ratiba_dz16 الله يبارك هاذوا اللي لازم تفتخر ...
233997                @IkrameAlger النور نورك ربي يحفظك 😘
233998  @Ania27El بصحتك انيا 😘 واش تحبي نجيبلك من جيجل...
233999           @Ania27El ومااكثر المنافقين في هذا الزمن

                                                     text
234995  @SenoriitaFresco @Reemkhaney يلا بدعييلك من كل...
234996  ههههههههههههههه اقسم بالله لما ارجع للتاج امبا...
234997  @turkiyenew واضح الفانز كان مستني ردة فعل سينو...
234998  @SenoriitaFresco @Reemkhaney مرررررررررررررررر...
234999  لا انا هنا خلص النقاااااااااااااش مع البنت دي ...

                                                     text
235995  @saadlamjarred1\nهام :\nفانز بليز كلنا نشتغلوا...
235996  @saadlamjarred1 \nيلا فانز الكل يشتغل باليوتيو...
235997  @saadlamjarred1 \nنيالهم الفانز يلي بيتصوروا م...
235998  @saadlamjarred1 \n\nبصراحة \nشو شعوركم لما تشو...
235999  "مغني جزائري يتمني لو كانت اغنية سعد لمجرد سال...

                                                     text
236995  اللي بحياتي كلهم اتهاوش معهم مو موفرة احد\n😂وب...
236996  11/07/2016 اليوم اللي فرحت فيه من قلبي https:/...
236997              @Faddine عادي مش شرط الكل يعرفو يعومو
236998  في اشياء مانقدر نقولها لاي احد https://t.co/rP...
236999  بسيطة بسيطة \nعبيط وعبيطة\nبغاها وخطبها\nووافق...

                                                     text
237995         @bilal_1102 الله يسلمك تعيش 🌹\nربي يحفظك 🌺
237996     @Oct____14 الله يسلمك أحلام ربي يحفظك ختيتو 😘🌺
237997            @mounadz_ منوش !!\nصباح النور والسرور 🌹
237998  @nasimalgazair ربي يرزقك من أوسع ابوابه يارب 🤲...
237999  @donia____doudou وين بيها ختيتو ان شاء الله خي...

                                                     text
238995  @TurkeyCelebs باهاالسرعة ناطرين التشين على نار😍😍😍
238996  @sloom_sg بتابعو من شان نجمتي البرتقالية التشو...
238997  @Murat_Turki فعلا حتى بعض الفانز العربي مو حاب...
238998  @raselnfc11 ربي يلطف بينا في الاخير احنا اخوة ...
238999   @TurkeyCelebs البشع والبشعة لايقين على  بعض كثير

                                                     text
239995  @Visite_Algeria قسما بالله ولا مرة في حياتي وح...
239996              @zdeldeul يا ماما حابين ياكلونا 😭😭😭😭😭
239997  😭😭😭😭😭 خرجوهم علينا مارقدش من الخوف يا ربي راح ...
239998  @Walidoo75470444 لي يخاف على بلادو ويتعاطف مع ...
239999  @4algeria يتجرأ ويفتح سوق او اي تجارة غير شرعي...

                                                     text
240995  @derradjihafid الله غالب الجزائر وما أدراك ما ...
240996  #راني_زعفان بتهجمك على انس تينا انت راح تستفيد...
240997  @ya___sou ما فيها والوا هذا جزائري و عبر على ر...
240998  تاغيت و النخل 🌴\n#هذه_بلادي_الجزاير https://t....
240999  @lotfi07994484 بسبب سياسة البغفلون انتشر #البح...

                                                     text
241995                  الزهر مكانش ولا انا لي مكانش ....
241996  سلمياني اعتزل خخخخخ شغل ميسي كي يفشل المنتخب ي...
241997        المطر ينزل اللهم غيثا نافعا🌧️🌧️🌧️🌧️🌧️🌧️🌧️🌧️
241998                 جا ولا مزال والله كنت في العمل 😂😂😂
241999  خاوتي كاين لعبة مش مليحة للاطفال يقدرو حتى ينت...

                                                     text
242995  هههه جهة قادر وبن جخير شفناها اكثر من جمهة غاز...
242996  ههههه خالد يحب غازي المطيري يعني مو شي جديد هذ...
242997  هههه غازي تعب ف الطبخ والشمس فوقه ب الاخير راح...
242998        نشا الله غازي يفوز ف السجن هههه #زد_رصيدك86
242999  ما اعرف الطبخ السعودية بس احس الفريقين طبخو تم...

                                                     text
243995           @SpecialOneDz فحلة وامراة تاع الصح برافو
243996  @maya_____1 روعة جمهور عالمي شيء خرافي بإذن ال...
243997  @BenaliaMohamed @IssamLFC1 رسمي كاشما راه شارب...
243998  @MinouMano ماعندهاش علاقة بالميدسين شخصيتي جاي...
243999  @sanaa_rahaf شكيت فيها بصح مانيش متأكد يعني هو...

                                                     text
244995  للي بيسأل ليه خاشقجي تحديدا، الفيديو ده بيكشف ...
244996  للناس اللي بتقول مفيش تسجيلات ودي خرافة.. سلم ...
244997  اسقاط بن سلمان موضوع بالنسبة لي صعب، كل ما يحد...
244998  حمو بيكا: ياللي جاية معاك بخصومة.. احنا أخطر م...
244999        @MUSAB__FUAD هي عيلة مفيهاش حد يفتح النفس 😂

                                                     text
245995  منتخب الناشئين الهاندبول كسبان البرتغال فرق 3 ...
245996  @ilinanasser أيا كان اللي فهماه وخمنتيه، العشر...
245997  من أغرب الحاجات في العالم الناس اللي تإذيك مرة...
245998  @espressos_man انا عايز واحد من ذرية زوبا وتشا...
245999  والله وأنا بنام بدري امبارح وفي ذروة النكد الل...

                                                     text
246995  @Ahmed_F512 الله يسلمك يارب\nمعقولة ابقي لجنة ...
246996  لن اعير انتباهي\nالا لاصدقائي\nاللي عارفاهم😂😂😂...
246997       @mon1_m هو ده اللي حصل معاية\nبس ده اول مرة🙋
246998  عندك كل الحق والله ياباشمهندس\nحمدالله عالسلام...
246999  في يوم قولتلنا\nمصر ام الدنيا\nوحتبقي قد الدني...

                                                     text
247995  ربنا يكرمك يامارك ..سيبنا نتكلم زى ما احنا عاي...
247996  في ناس محترمة ، لما تحب تحرجنى تقولى متنسيش ان...
247997  أنت معاك رصاصة وأنا معايا قلم \nتقدر ترسم سحاب...
247998  يمكن ربنا ينفخ فى صورتنا لو نجحنا فى الثورة دى...
247999  الحاكم من دول يقعد كاتم على نفس شعبه مدعى انه ...

                                                     text
248995          @Haneen03132581 احيي روحك دي .. اشكرك 🌹🌹😍
248996  وقف شاعر ع شط البحر وأنشد يقول : يا بحر جئتك ش...
248997     @Haneen03132581 شيل .. ومترجعش بيها تاني هنا 😠
248998  أهواك في قربك وف بعدك .. واشتاق لوصلك وارضى جف...
248999  قبل ما تهبد وتشتم في الحكومة ونظام التعليم ......

                                                     text
249995  @maganenoo ده التايم عندها كله ع مصر \nوبقله ا...
249996  @acc_shahdessam @Rola_Cc الليله يابنات بدايه ا...
249997  @sherin0409 @Bassem_Mourid @iambaderkhalaf قلب...
249998  @Rola_Cc @acc_shahdessam حلو قوى بس ٨ حيكون ال...
249999    الاخوه من لبنان واليمن ماتخليكوا ف حالكم المايل

                                                     text
250995  @MeryClue دول مبيفهموش قنصل ايه !! انتي وزير خ...
250996  @KhadigahOwus16 @MeryClue يرزقنا ازاي وهي محتل...
250997  @_King_of_Mars @MeryClue @KhadigahOwus16 اول م...
250998  @AhmedDodo87 يا ابني كده كده هنخلص منك يوما ما...
250999  @MME_Hope @_King_of_Mars @MeryClue @KhadigahOw...

                                                     text
251995    @EmanAttia122 @luleetaluli هما خلوا لنا ذنوب 🙈🙈
251996  @PhobiaMad بحترم الناس اللى كدبهم مفضوح دول .....
251997  @Mohsen @Mirna_elhelbawi @NRJEgypt ربنا يخليكم...
251998  @NadaAbbasShams وانا كمان والله :) سﻻمى لماما اوى
251999  @MOHSENse  دلوقت علي راديوهيتس مع زهرة،،صباحكم...

                                                     text
252995  أنا كُنت إمبارح فى وسط البلد بحضر مسرحيّة فى ا...
252996     براحه يا ناهِد مش كده! https://t.co/a44xdCSZRE
252997  @a7madgenedy مديرك جميل اوي ياحمد، ربنا يخليهو...
252998  يابيه احنا شعب بيفرح لما يركب المترو المكيف .....
252999  دخل عندنا فار فالمطبخ وهاتبقىَ ليلة سوده مافها...

                                                     text
253995  @Ranya_Masr مُمكِن صُدف، لكن إيه اللي مُمكِن ي...
253996                       @eslam18 دا عرض مش معاكسة 😂😂
253997  @monicamayz368 خلاص بقى يا مونيقاا مش ناقصة قر...
253998               @monicamayz368 مانا عارف بس بستعبط 😎
253999  أسافِر .. وبعد ما سافر وارجع أسافِر تاني ولمّا...

                                                     text
254995  #يلا_سيسى واحنا معاك مش هنسيبك ولن نجعل للخونة...
254996  @Elgehral @MyTrueHope اتكلمي كلام معقول دا مخا...
254997  @blwar2awel2alm @MyTrueHope ماهي دي ايامه كل ش...
254998  #يلا_سيسى وريهم العين الحمرا عشان يعرفوا حجمهم...
254999  @Nabawia73 خليك في مشاكلك يا تميم انت قريب هتح...

                                                     text
255995  @hkhedrofficial امال الاغريقية والهندية والسوم...
255996  @hkhedrofficial وليه بقى مظهرش؟ ملهمش نفس للهد...
255997  @hkhedrofficial قصدك ان الشعوب اللي عندها دستو...
255998  @hkhedrofficial @putatif طب ما الحيوانات بتتكا...
255999  فيلم البيه البواب بيبدأ على ستار سينما .. من ا...

                                                     text
256995  @ashraaf_alsaad لأن وصفهم ب"مؤمنين مذنبين" بيد...
256996  الحرباية بتلمع التعبان الإنجليزي. عمره مادعم ا...
256997  مبروك يا @Amradib جالك مرشح رئاسي أونلاين عشان...
256998  #شفيق_خان_مصر واللي يخون بلده ويهرب منها في عز...
256999  @kokydraz والجزيرة كانوا عارفين ان بنته بتصور ...

                                                     text
257995                     @Ahmed_Abrass لا ده خطر هههههه
257996   علم في المتبلم يصبح ناسي https://t.co/2HuBFPEM6C
257997  @ZemaOfficial @RaniaKeiy انت جيبت منين سرقة مج...
257998                       ليه اصحى دلوقتي يوم الجمعة 🤔
257999  @Nermbed اه طبعا و الواحد كان قاعد في بيت اهله...

                                                     text
258995  فيلم saw بيديني كميه افكار رهيبه ازاي اقتل بيه...
258996       عندي احساس ان فالنسيا هيتعادل ف اخر 10 دقايق
258997  رساله لزوجي المستقبلي لو ليا نصيب ارتبط واتخطب...
258998  الفترة الاخيرة دي غالبا مفيش حد اتكلم معايا غي...
258999  رابطة اللي زهقوا من محبي الفراخ المجمده ومن كا...

                                                     text
259995  @medo10boss @skay_blow @Bent_Elgohary3 @EmanSa...
259996  @medo10boss @Osama_1_Raslan @doaaqeshtaa @2z35...
259997  @medo10boss @egyptlady5 @Osama_1_Raslan @Doaaq...
259998  @alexandriamoham @Ganet_elyasmen @magdyelmarsy...
259999  @medo10boss @alexandriamoham @Ganet_elyasmen @...

                                                     text
260995  #احنا_معاك_ياريس : ومعاك ياريس فى تنظيف بقية م...
260996  #احنا_معاك_ياريس : السيسى لما استلم مصر \nكانت...
260997  @05moham علشان خاطرى ياواد عمى صورلى الصاوره ع...
260998  @05moham يبقى دعواتك لمصر من بلاد الحرمين..وتر...
260999  @omomar5200 اصبرى اصبرى ..اهوه ظهروا ظهروا😂😂👇👇...

                                                     text
261995  @almifarhkuw @Raed2525 ياحمار هات لي واحد عالم...
261996  @4OwJWNd8Rxqzmws @almifarhkuw @Raed2525 ما انت...
261997  @FaragEsmat @Hendalthani1 @h_tamimi9 والله عيا...
261998  @Raed2525 @almifarhkuw اي انزل في شبه الجزيره ...
261999  @almifarhkuw @Raed2525 هههههه مهندسين ودكاتره ...

                                                     text
262995  @eltonsy70 احنا لو دافعين لفهم فلوس عشان يفضحو...
262996  اختار عايز تكون جندي تدافع عن بلدك ووجودها وكر...
262997                       هو كدا لازم اعلامنا  يلاعبهم
262998  مش فاهم انهي حمار فاهم ان لو البلد وقعت ودخلت ...
262999  @sherinhelal555 ربك كريم ومصر محفوظه وان شاء ا...

                                                     text
263995  @bakr123azzem بقت كاذبه صدقني الثقه في النفس و...
263996            @AbdalmenemAyman تنور في كل الاحوال ...
263997  @eid_fouad طبعا أكيد كلنا بنتشتم والشتيمه بترد...
263998  @eldeeb_mosa يتهني به يا موسي ..وياريت يحتفظ ب...
263999  @kemo138721 بيحب يبعد الازعاج عن الناس الرايقه...

                                                     text
264995     @om02ahmad تسلمى يارب على الورد الجميل ال مثلك
264996  @BasmazizAziz حبيبى ياباسم ده نورك العاكس ياصاحبى
264997  @BasmazizAziz حبيبى الغالى ابن منطقتى #بنى مزا...
264998  @Norhan1Mahmoud #الاهلى\nكبير وهيفضل كبير\nمش ...
264999  @Devil9091 @nihadnano16 @Bilalisgoren مين فضيل...

                                                     text
265995  @TheXela دا روحى وحبيب قلبى الغالى 😍 والله نفس...
265996  @TheXela @drrashasamir والله كنّا فى سيرته بال...
265997  @hosny54 مش متابعة اليوم السابع 😂 مين بقى 🙏🏼 ط...
265998            @hosny54 🧐 دى ممثلة ! مافيش غيرها بال غ
265999  @ehab34anTel @m_abohossam2 خليهم ينتفضوا بلا ق...

                                                     text
266995  @sammorme مش اوى كده يا دكتور \nبعدين اتغر فى ...
266996   @sammorme متشكرة اوى يا دكتور \nربنا يجبر بخاطرك
266997  @sammorme صدقنى يا دكتور اهلنا اللى حضروا التأ...
266998  @sammorme اهلنا حكوا لنا انه كان فيه مهندس فى ...
266999  @Nefertery_Ahmos تسلمى لى يارب \nانا برضه دخلت...

                                                     text
267995  …العيال ناموا 👀\n::ايوة يا حبيبى ناموا 👱‍♀️\n…...
267996  فين الشتا يا سيسى \nوديت الشتا فين \n\nبقى ده ...
267997  يابني احنا بنشتري راجل لا يفرق معانا عندك كام ...
267998  واحده بتسأل شيخ\nليه الزوج وزوجته لما بيكونوا ...
267999  سأل زوج زوجته وهما عالسرير قبل النوم :\nإنتي ع...

                                                     text
268995  @khaledmontaser خلاص ياسميه بعد كلامك ده مبقتش...
268996  @MohgaW @___Sinuhe___ لا معلش بقي الموظف اللي ...
268997  @KarimRamzy @Mohamed47639600 معاك زي دي😂😂😂فضل😂...
268998  @magedgamal112 @__shimasaber عارف نفسك قرد يعن...
268999  #جمهور_الاهلي_عنصري_للاهلي\nاوعي تفكر ياشوال ا...

                                                     text
269995  #سبعه_عالمحطه\nالهبده اللي بستناها\nان عليش رج...
269996  @a7med0ramadan @KhaledEleish والله انا مستنيه ...
269997  @a7med0ramadan فاهمه وعامله عبيطه 😜\nوالله قول...
269998  @a7med0ramadan ربنا يستر علشان بقى يتحول عليا ...
269999  في حد معين لو جبر بخاطري النهارده \nبإذن الله ...

                                                     text
270995  عندي قناعة ان محلات الملابس الحريمي لازم تعمل ...
270996  في مكان ف قعر جهنم ل ولاد الوسخة اللي بقفوا ع ...
270997  طب بالنسبة ل يوسف غالي وممدوح اسماعيل و رشيد و...
270998  يا بخت من بكاني وبكي عليا ولا ضحكني وضحك الناس...
270999  حجم حلمك هوا اللي بيحدد حجم الخازوق اللي هتاخد...

                                                     text
271995  الناس شيفاكي غلط معرفش ليه بس انتي جميله فشخ و...
271996  مزغوده ومن الناس القديمه اللي بحبها وفكريني عا...
271997  حقيقي انتي اكتر واحده انا نفسي اشوفها مبسوطه و...
271998                           كيرلي فيرلي هايش يا حلوه
271999                   محتاج فعلا ارجع لورا خمس سنين بس

                                                     text
272995  #صاحب_تويتر_وفلورز_للخميس عايزين فلورز للخميس😉...
272996  #اشهر_كدبه_في_البدايات اجتهد عشان تاخد كورس بر...
272997  #الزمالك_راجع_تاني 🎤راجع بتقولي اللي ما بينا و...
272998                       #بحمدك_يارب_علي كل شي وكفي❤️
272999  طب هو فى حد عاقل يفضل صاحي لحد دلوقتى وعندو شغ...

                                                     text
273995  اقسم بالله تويته كلها positive energy\nانا كده...
273996  من غير الفاظ قذره\nوياريت كل واحد يخليه في حال...
273997        @kokydraz ياريت يا شيخه ده يستاهل مليون قفه
273998  @Ra3_The_king أنا مش زعلانه منك\nرغم أني معرفك...
273999  @SaqerBasel حلو قوي يا بيسو و كل سنه وانت طيب ...

                                                     text
274995  الواحد بقي ينزل علي الصلاة بالظبط علشان مايسمع...
274996  @MonaMahgoub0 ما انتي غلطانه برضه يا مني .. از...
274997  لو حد فهم حاجة من إجابته علي حوار سد النهضة يا...
274998     @Muhamed3amr ، 😂😂و انت تعمل دايت ليه يا عم انت
274999  😂😂 كل مرة اقراها غلط فعلا https://t.co/I6xkKZVcBE

                                                     text
275995  فعلا اللى بيحبه ربه بيحبب فيه خلقة وانت راجل م...
275996  @mogaber45 انا بعمل حظر على طوال دول مغيبين وا...
275997  @mogaber45 حضرتك انا حولت كتير جدا جدا دول فعل...
275998  والله الفرحة كبيرة قوى قوى النهاردة ربنا يديم ...
275999  من ام الدنيا بقولكم كل سنه والجميع بخير اخر مر...

                                                     text
276995      وعاوزنا نرجع زي زمان قول للزمان إرجع يازمان🎵🎶
276996  ترووح مول تحس إن مصر كلها في المول تروح سينما ...
276997  @Amr_Desoki كفاية إنت ملاحظ من زمان هايبقى في ...
276998            نفسي أشوف حد لما ياخد قرار يبقى قده بس.
276999  المبرر إن الدولة إلي كانت بتدفع للناس الوسخة د...

                                                     text
277995  @R2gmfNae6XjhzyO @amice__ @Mr_atia_ طب الحمدلل...
277996  @R2gmfNae6XjhzyO @amice__ @Mr_atia_ أولا  *هنا...
277997  @R2gmfNae6XjhzyO @amice__ @Mr_atia_ تسلم يارب ...
277998  @Montasserbakry الله يسلمك  ..\nكل سنة وأنت طي...
277999  #مصر_تخوض_حرب_وجود\nالمعركة معركة وعي و إدراك\...

                                                     text
278995  @NawalElZoghbi @ELAdlMedhat @AmrMostafa انت را...
278996      @suhad_majzoub ياااااريت 😂😂😂😂دي بنت محظوظه 😂😂
278997  #كريم_عبد_العزيز #شريف_منير ❤❤ برافو بجد تجننو...
278998  كنت منتظر ايه يا ابن موزة بعد قذارتك وخيانتك h...
278999  @karimfahmi كلامك في برنامج شهريار عن المرأة و...

                                                     text
279995  @ehab34_antel يامسهل \nمش عوزين البربر يخدو بط...
279996  @Shahdtenaah خاصة ولا حكومي خسارة في اهلها عال...
279997  @RadwaHa14480540 @Shahdtenaah اخرسي ياحقيرة ان...
279998  @RadwaHa14480540 @Shahdtenaah اعملي بلوك للواط...
279999  هو حد قالك انه بيطلع يتفسح ولا حاجه\nطب ماتقول...

                                                     text
280995  @DMCSports جيد بالنسبه للاعب مش اساسي \nعنده ا...
280996  @AmirMortada 🤣🤣🤣🤣 كان قصدو ع الزمالك محدش يفهم...
280997    @DMCSports مش متعود ع المركز الأول حاسس بالغربه
280998  #للخلف_درر_يا_زمالك\nوبامبرز كمان مفشوخ،  وخرب...
280999  @WaelGomaa @DhiabTarak @AlAhly نورت بيتك يا صخ...

                                                     text
281995  @SameraSabra رحمه الله عليهم حبيبتي وربي يكرمك...
281996                 @hesham_m_2011 ومنع السفر رايح جاي
281997                       @sorromba2 لا هو حبق للمغص 😄
281998  كمين بنزينة النصر في وسط البلد اتضرب وانباء عن...
281999  @AymanAl89669031 تعامل مع الكمين اللي بجامع ال...

                                                     text
282995        @kiki7520022 هنعرف .. الحاجات دى مش بتستخبى
282996  @Turki_alalshikh انت فاضى ياعم ولا صلاح عملك خ...
282997  @MonyNKamel ده مش حك فى ٣ شركات كانت داخله الم...
282998  هما ٣ اطفال اللى فى الصوره دول ولاد مين عشان ه...
282999  مليش انى أتكلم فى اللى بيحصل فى الاردن هما احر...

                                                     text
283995  @aziz_nany باحاول افكر فى اى سبب خفى عبقرى لوز...
283996    @aziz_nany لازم نحط اى تاتش فصيل فى اى مناسبة 😐
283997  @Mrhossam33 امتى فى طول عمرنا كان عندنا ميسي ب...
283998                   @cookie_shm مين بقى البنات دول 🤔
283999  @WilloEgy @ashrafthewand\nاعتقد انه بيقول اللى...

                                                     text
284995        ياحلو صبّح ياحلو طُل\nياحلو صبّح نهارنا فُل
284996  إصحي ياعامل مصر يامجدع وإفهم دورك في الوردية\n...
284997       حلو قوي قطع العلاقات اللي على وش الفجر ده =D
284998  =إحنا نقطع العلاقات مع بورنجا العظمى علشان تبع...
284999  يارب\nاللي يصون الأرض يسلم\nواللي يبيع الأرض يولع

                                                     text
285995  @mezoElX اكهربااااااا احبيب قلبي هنردلهم اللي ...
285996     @mezoElX ما حاولوا ياخدوه قبل ما يروح الاسيوطي
285997  ربنا يخليهولكم ويرحم والدتك. https://t.co/5GCI...
285998  في تركيا اسمها معاناه وعقاب..\nعندنا بقى اسمها...
285999  الحرب الأهلية في لبنان قعدت سنين طويلة ومعظمكم...

                                                     text
286995        هو الماتش هيتعرض على قنوات إيه يا جدعان !!!
286996  إنت عشان تشجع كورة فى مصر دلوقتي مش لازم تكون ...
286997  مفيش حاجة في الدنيا أحلى من انك تشوف\n حته منك...
286998  من ابسط حقوق المواطن المصري البسيط وإدخال الفر...
286999  تحس نفسك لوحدك ، فتعمل حجة وتفتح موضوع مع حد ع...

                                                     text
287995  وانا بصلى واحد معدى من ادامى ...فمديت ايدى علش...
287996  - روح يابني ربنا يبعد عنك خبطات صوابع الرجل في...
287997  مجتمع معاق فكريا لدرجة ان الى بيكرهك بيهتم بحي...
287998  واحد بيتخانق مع مراته قالها خايف اقول عليكى حم...
287999  بتحب ناس متتحبش ، وتعاشر ناس متتعاشرش ، وبتكتب...

                                                     text
288995       ما شاء الله وكمان فيه طفولة #ضيعت_طفولتي_علي
288996                      حب الحق والخير #شخصيتك_ف_كلمه
288997  ميسي عايز ياخد الجذمة اللي اتبرع بيها لمصر .. ...
288998  @AhmedElahmar اللي دايما رافعين راسنا ف السماا...
288999    الوحيد في مصر اللي جنن الطرطور #خرجوا_سيد_مشاغب

                                                     text
289995      مساؤكم معطر بذكر الله https://t.co/bgpOcS4XyS
289996  @____Nena____Zak هولاء مع يمشي مع مصالحهم\nبمب...
289997  @Maha_SalahElDin تتحدثون عن النفاق وأنتم أهله\...
289998  @EzzatLisa ده جناح سمير وعلي ولا ايه😂😂😂\nمساؤك...
289999  @kemo138721 امين يارب العالمين ربنا يعزك ويسعد...

                                                     text
290995  #لو_مليونير_هتعمل_ايه فلو وخد الباك في ايدك وا...
290996  #لو_مليونير_هتعمل_ايه هو استفسار بس هي العملة ...
290997  #لو_مليونير_هتعمل_ايه مش عارف انام طيب حد ياخد...
290998  #الهلاسين_بيقلشو_و_ينكتو طيب انا دمي تقيل جدا ...
290999  #الهلاسين_بيقلشو_و_ينكتو الجروب ده يصحي كدة وي...

                                                     text
291995  @5aldsliman اهو صلح الغلط و طلع مهاجم و نزل فت...
291996    حجات بسيطه بس تفرق كتير https://t.co/PUTrMol4IC
291997          @EsraaFawzy_H ان شاء الله ربنا هيظهر الحق
291998  @SAheRmostafa96 @m7md96radwan و انا يا عمده يع...
291999  @mohamedradybeeh ده هيحصل تعشيش بالعبيط مفيش م...

                                                     text
292995  بيقولك بطولات حلال \nكسم حضراتكم 😂😂😂😂😂 https:/...
292996         @AhMad_Gamal_ ده جول التعادل يا احمااا 😂😂😂
292997  @AhMad_Gamal_ بس ياعم عليا النعمة هكسم الزمالك...
292998  وانا بتفرج ع التايم لاين 😂😂😂😂 https://t.co/uvO...
292999  تايم لاين بعافية شوية احا الواحد يشيش ويفسى دم...

                                                     text
293995  هي جمعيه ودايرة ..قبله عكاشة و عمرو الليثي واب...
293996  #مدحت_شلبي دا مسخرة بيقول لكهرباء شوفلي فيشة ج...
293997  الصورة التذكارية للزعماء الافارقه\nاستخرج صورة...
293998  البيضه بقت ب2 ج\nفياريت نحافظ على ال4 ج اللى ح...
293999  لقاء بين رونالدينهو وجورديولا\nايه اللي مميز ف...

                                                     text
294995  @ahmedmahallawy1 هو حضرتك بتقول ايه\nعامل بسيط...
294996  @ahmedmahallawy1 بيجرب السوق!!!\nماشي يا استاذ...
294997  @ahmedmahallawy1 واضح ان حضرتك ماتعرفش السوريي...
294998  @ahmedmahallawy1 ياعزيزي انا باتعامل معاهم من ...
294999  @ahmedmahallawy1 حد..بقولك من ٢٠٠٧\nيجي سبعتلا...

                                                     text
295995       بس يجيي اليوم ده  😢😂 https://t.co/vU1T00zLeU
295996  #كلمه_لشخص_اتغير_عليك الله يسهلك طريقك بس بعيد...
295997  المفروص ان دوري الابطال السنع دي ميخرجش من مصر...
295998                   #مش_فالحين_غير_ف كلمه معلش  😂😂😂😂
295999  @mohamedsaeid203 كلامك صحيح   بس دا ميمنعش انه...

                                                     text
296995  حد فينا لازم يموت انا او ضميري\nوعشان كرهت الس...
296996  نازل عشان الشهداء\nنازل عشان البنات المعتقلة\n...
296997  اوبا عيب كده يا اخونا هدوم ايه اللي هيلمها هو ...
296998  @sohila_mostafa تصدقي ان انتي اللي بهيمة يا شو...
296999    الوضع مش هيتغير\nوهيفضل صلاح هو صلاح\n#_علي_سعد

                                                     text
297995  لا انا مش عايز  منطقة الفحص الجبهي دي حضرتك ht...
297996  بحب اللمة مع عيلتي و الخروج معاهم جدا و اكتشفت...
297997  نتوكل علي الله و نمضي 😃\nاول خطوة في الحاجة ال...
297998  @Ahmed_H_Hammam حلم حياتي يا خي والله 😅 \nانت ...
297999  @Ahmed_H_Hammam جاي عرض .. بس لسه بدرسه مع وكي...

                                                     text
298995  @dw_arabic المفروض نكرمهم ولا نعمل معاهم اية ل...
298996  @imansef السؤال المحيرنى هو عدهم ازاى\n\nوغير ...
298997  @imansef وغلوتك بطلت اتخيل  هنتخيل ايه ولا ايه...
298998  عارفه لما يكون كل تفكيرى فيكى\nومبطلبش منك غير...
298999   @Sweet2009Heart ربنا يروق بالك  ويحسن مزاجك ديمآ

                                                     text
299995   @antibiotic2030 النضارة السودة هي السبب يا ضنايا
299996  @GhadaKhalifa10 @Azaziil @daliaAO شفتي... دليل...
299997        اهو قاعد يصطاد الغلابة 😂😂😂😂😂😂😂\nعيل سَوّ🤣🤣🤣
299998  @Eldone01\nكل سنة و انت طيب يا راجل يا طيب و ع...
299999  @TrueXela مش إنتي... مش انتي ي ي ي ي ي ي\nاديك...

                                                     text
300995  #السيسي_هوا_الرييس التايملاين النهارده كله عن ...
300996  @maganenoo بيقولك هو ميت قي السجن بس هما عاطين...
300997  @Lforlomy معروفين ومعروف مين الي بيدفع لهم علش...
300998             @HendSalem61 لا ده بانجو نوعه عالي اوي
300999  @1st_is_EGYPT @aa_arabic يصدق او مايصدقش هاتفر...

                                                     text
301995  @elabadlawy @helpegy2 كان زمااااااان هو الكلام...
301996  @OshaElmala7 مش ای حد لان الجیل ده قلیل الی بی...
301997  @magez__ قدیمه فی هاقولها\nراجل وابنه واحفاده ...
301998  @rogina91 کان سایبهم لیه من الاول والحکومه عند...
301999  @sinawia2 انا عن نفسي بخش المحل فيه اكتر من نو...

                                                     text
302995      @mkahal_h ولله كل شي بيتصدق مافي شي بيطلع كذب
302996                @mkahal_h ان شاءالله يكون كذب مش صح
302997  @OneMaestro1 بعرفا منيح بس شكلك مضيع البوصله ل...
302998  @OneMaestro1 نحنا ديماً موجودين بس للأسف حضرتك...
302999  هيدا يلي طلع مع القوات عم يحرضو العالم ضد الجي...

                                                     text
303995                                سؤال غبي وجواب اغبى
303996               @Batool10727873 اعملي ميوت ونامي يلا
303997  تمنيتلك شي وسخ متل هالأمنية بس تركتو بقلبي htt...
303998  متل الزوج اللي بيضرب مرتو\nحيوانات وناس مريضة ...
303999   @Bouchera_2 "شعب بينو وبين التفاهم في سوء تفاهم"

                                                     text
304995  بعد ناقص المخزومي يبعت جمهور يحمّسوا بالملاعب ...
304996  الحرب بين المرشحين صارت مين بيجمع ناس اكتر، بع...
304997  هيدول القرشين النضاف لي بتقول خليني استفيد فيه...
304998  رجعوا عالصف، اشتروا البرامج الترفيهية والكوميد...
304999  يا ريت بقى تسحبوا الولاد عن الشاشات لأنو بيكفي...

                                                     text
305995  @gharios_souad بالتوفيق انشالله\nبنتي نجحت برو...
305996                @Iman_M_Amin شو؟ منقول بروك النجاح؟
305997                     @monaazar_ مين الام ومين الكنة
305998                    @YounisKasim ما في حدادة وبويا؟
305999  ..اما الحملات الصليبية\nوالانتداب الفرنسي\nوال...

                                                     text
306995  @wehby_Abeer عبير انا ليه دايما بس نام بفوتني ...
306996  @hsnita95 @hassankansoh هيدا بلا اخلاق وحرام ن...
306997  @HassaniehL جد كتير صعبة الترباية هل الايام لل...
306998  بنت اختي هي حرة\nما حدا بيسترجي يشارع فيها htt...
306999  ثورة شو يطعمك الحج والناس راجعة https://t.co/0...

                                                     text
307995  @lebouss بتعرف صرت بقول بيني وبين نفسي اذا ماخ...
307996   @lebouss بتحس كره عمرو سنين من الطائف يعني مثلا😜
307997    @sharifhejazi مشغولين نحن اصلا مش فاضيين لترامب
307998  ياخوفي ينسحب الوفد اللبناني لك والله بتفضى الق...
307999  يعني ورقة التواليت بعد ماتمسح مؤخرتك اغلى من ا...

                                                     text
308995  @Mhamad__krayem عفاك 🤣👌 تشوف مين بالحكم ومين م...
308996  عرف انو صار عليها ضريبة ؟ او لم يكن على علم .....
308997  يعني ما بقى في تيار شيعي ثالث ؟ 😥 https://t.co...
308998    @Eben_Eljiran مبلا جد هون كانو بالضيعة عندن 🤣🤣🤣
308999                  @Eben_Eljiran اي كان صغير .. هاها

                                                     text
309995  ههههه هيك صار بال #هبلان_الثلاثي https://t.co/...
309996        @raniajbr 😂😂😂😂🤧يبعتلن قواص متل ما بتدعي ستي
309997  ب #انتخابات٢٠١٨  ب #لبنان مستعدين يفقولك الحبو...
309998  @Jad_Ghosn هلأ بيتاتنا مش غريب كيف هاجمين عا ب...
309999  @Alinmajed صديقي مش ماشي غير الأكل و القهاوي ....

                                                     text
310995  أصلا شو هالكفر\nلازم يقولوا: عمرك أطول من عمري...
310996  اللي عم بعلمني سواقة قلي اليوم "اشتقتلك" وقلبك...
310997  ذات مومنت لما ترجع عالبيت وتلاقي الوالدة واتشي...
310998  بما إنو دارجة الصراحة هاليومين، بدي صارحكون إن...
310999  مولع سيجارة بال ascenseur ومحمم بالعطر العربي....

                                                     text
311995        @ayaazamet @LebaneseCrush شو لكن ما في مزح😌
311996                     @ZanzounHNY عنجد اد ما عميقة 🌚
311997  @YaraJoumaa @JLouji خلي خدودك يلي بلا غميزة ين...
311998  هيك بيخلص مشروع الروحة عالمسبح يلي منخططلو انا...
311999           بعد جمال البنت اللبنانية ما في\nمنتهية..

                                                     text
312995  @VMakhzoum المشكلة تعودنا عالاشيا الغالية وكل ...
312996  @DimaSadek يلا بعد عندك هالكم يوم لحقي حالك وت...
312997  انتخابات بعلبك - 1996\n#نحمي_ونبني https://t.c...
312998        @ramzi_eid29 هههههه بعدك سهران ؟ وتارك لبيك
312999       معروف سعرك يا قشطة 😍 https://t.co/sbEsVqrfXJ

                                                     text
313995      @y7mYmFGvbUg8V4t يسعد مساكي بالورد وانتي بخير
313996  @SaharMShawky عنا بعكار كل اسم سحر بيقولولو كر...
313997          @SaharMShawky سحر بعدين كرمال عيونك بنتحر
313998  @SaharMShawky الله يسلمك لاقرب حاجز وكون انا و...
313999  @HGharzedine كلام جميل يسعد مساكي الحياة هديه ...

                                                     text
314995  @Nada_Andraos لو شي واحد من الحدث شربان كاس وش...
314996              @samarabukhalil قوية يا فخامتك هههههه
314997          @SleimanMichel يا عمي... إنت بعدك بالبلد؟
314998  @KaramRachel @carolmalouf @SleimanMichel ايه و...
314999                            مين يعني عصام أبو جمرة؟

                                                     text
315995  عمر دياب اذا بي ضل عم يصغر هيك بعد سنتين بياخد...
315996  طلّ علينا و مسّينا\nمسّاك الخير❤️❤️ https://t....
315997  لك مطلق الحرية أن تعيش حماراً.. \nبس ما تلبط ب...
315998                @RMA_Sara على اساس معو فريق و لعيبة
315999    @aljanoubabak الله يسامحو\nكان لازم يقول تجحشنا

                                                     text
316995  @aliitany6969 ما حدا عم يروق بالسواقة واكيد ال...
316996  @Abir_Boubaa مش غلط واذا بيقدر يحمل الطاولة ما...
316997  @Kamilia21253360 ع فكرة هالحثالة من البشر بيهد...
316998  @WalidAlOmary يا جماعة اصحاب المتوسيكلات لا يح...
316999  @WalidAlOmary اقسم بالله العظيم ما بصدق اوصل م...

                                                     text
317995                @tiger_damen والله مسيتها ثواني بس😂
317996  @NadaGhanime اجمل شي انو هو مصدوم ومتحسر عالفرصه😩
317997  #القوات_اللبنانية ما عندن رجال يحطولهم صور سرق...
317998  @HoseinMortada العمى من نص ساعه عملتلك متابعه ...
317999  #نحنا_مواطنين_مش_اوباش\nالوزير يلي بهين شعبو أ...

                                                     text
318995         @mabiraad وصلني مسج منك . صحيح. بس مافتحتو
318996  @louloulou122 @M_Hassanlakiss الله يسامحك.. ان...
318997  @Berry___H ما بتحس بشي .\nماهي لو بتحس .. كانت...
318998      @AZAL84 بتكون عم ترسم على شي من ورا السيلفي .
318999  @yupi_234 @TahaNsrdn هلأ بضهرها وزيرة الداخليه...

                                                     text
319995  @RabieFirawi هو كل جيل و الو جوه يعني مافينا ن...
319996  لو بدن يقتلو كل بني ادم بكفّر بلبنان ببطل في ب...
319997      ثقة الناس الزايدة بحالها يعني بتصدمني الصراحة
319998           ياخي حرير انسان كتكوت الفف والله بحبهااا
319999  كتير الحكي مبالغ فيه مجرد حكي بيحكي واقع يعني ...

                                                     text
320995  الناس اللي بتبعثلي على الخاص ممكن نتعرف. ريحوا...
320996  اكبر دليل انو حياتي غلط لما بشرب نسكافيه بنعس ...
320997  الناس اللي حابة تشرب كلوركس وتنتحر عرض خاص 😁 h...
320998  ما حدا مرتاح لدرجة رحت الصبح اعمل مناقيش قلي ا...
320999  بدي اسألكن سؤال و بتمنى تجاوبوا بصراحة\n\nطبّ ...

                                                     text
321995  ليش هالهجمة على كارول سماحة يعني بطل فيها الفن...
321996  @princelebanese2 ابسولوتلي من انت و زغير هيك م...
321997  @hpmqyuibfr96 @CAROLE_SAMAHA اي انا كتير بحبا ...
321998  @Jamal_Moghrabi @CAROLE_SAMAHA شعب ما بيعرف ال...
321999  @Jamal_Moghrabi @CAROLE_SAMAHA الحمدالله عايشة...

                                                     text
322995  اقسمبليه انه لو جاي بوراك تبع الاكل والمشاوي ك...
322996  @NourOusama اللي بمثل بمسلسل صاروا شي ٢٠٠ حلقة...
322997     @mmchhaar @charlesayoub6 مبلا الجمعة اللي بعدا
322998  @HichamHaddad57 عدمتي اذا بيجي تبع ورق العنب ل...
322999  @NourOusama مثل طيزك شو ما بيحكوا وخصوصا انه ا...

                                                     text
323995  @fa3eel5yr @Zeinabissa98 معقول ما تزور مليتا ه...
323996  الي من الصبح عم حاول احضر حلقة من مسلسل و صرت ...
323997               الله ياخد السوشي و اللي عرفني عليه 🙂
323998  مشكلة الواحد لما يبقا قمر مبيعرفش ينام بالليل🌚...
323999                البنات لبحطوا حمرة حمرا شو بحسوا ؟؟

                                                     text
324995  @news_ger_chekel حسب مين بجيب مصاري ومطلوب من ...
324996  @news_ger_chekel حمدالله مرتاحين من مارسيل وني...
324997  @safaa16111 عيب هلق الزعماء بيستنكروا بس يا ري...
324998  @news_ger_chekel خالص ويا ريت يقص هل الشعرات و...
324999  @news_ger_chekel متل وقت يموت حدا تاني يوم كل ...

                                                     text
325995     @LebISF اي والله هيك بيصير في مجال لنشتغل نحنا
325996                           @w_akl ع اساس هلا يا عين
325997  @KhatibRasha @AlakhbarNews @MayssamRizk يعني م...
325998  @SohaKikano @w_akl ليش بس يوصل لهيك منصب بعد ب...
325999            @NadimKoteich يلعن امك ع هالخلفي العطلة

                                                     text
326995  @ccchaaya @jarasscoop بإي حق يفرض على القطاع ا...
326996  @LbciLebanon @myriamklinkk من أنت حتى تقيمي الدول
326997  @KaramRachel @alsinani35 @ALJADEEDNEWS راشيل ا...
326998  @jarasscoop لك فشرو مين ما كانو، للسراي رمزيه ...
326999  @ManalEyoubi إذا فينا نشوف ربع الكبايه المليان...

                                                     text
327995  @saadhariri كلنا مع سلطة الدولة يا دولة،الرئيس...
327996     @jamil_el_sayyed اذا كان ترامب بنص التاني مصفر
327997  @may_chidiac @nuhasabbah لو مي بتنشرى بالمال ك...
327998          بدك تاكل اكبر بعد https://t.co/rirNHkLtLH
327999  الله يلعنك اكتر ما هو لاعنك يا خنزير https://t...

                                                     text
328995  @Elmarada يا ريتهم كانوا بالليرة السوري ، كنت ...
328996  @samir_jisr سمير الجسر ، بيغيب سنوات وهلق صحي ...
328997  @jeanassy كلام مزبوط يا جان ، بلبنان لازم ننطر...
328998  @Gebran_Bassil وزبال قوي وحرامي قوي وفاسد قوي ...
328999  @oscar_moussi ما حدا نبي ، جبران جزء من هل الس...

                                                     text
329995  #غلطه_ندمت_عليها\n\nكنت ف مستشفى العدان عندي م...
329996  #تفكيرك_وين_ايوديك\n\nخذها من اللي خذا عبره من...
329997  راتب شهر ٨  طاح في مجموعة صعبة:\n1- الحج\n2- ع...
329998                   عندي ٢٧٠ دك  وين تنصحوني اسافر 🤨
329999  سمحين ونعدي الغلطات ونمشَي\n            \nوالظ...

                                                     text
330995                    حلات الشارع من الناس (( فاضي ))
330996  بعد شوي اوريكم خطوات هاللوك عاليووووتيوب 😍 مع ...
330997                   وابتدى شهر القلابيسسس يا اوميس 💔
330998  فيديوي اليديد عاليوتيوب .. اعلمكم فيه شلون تكب...
330999  حالياًعاليوتيوب النسخة الكامله من فيديو تعليمي...

                                                     text
331995  @ben_dhim @lahvd45 غيرك واجد ..\nكحيلان يلطش و...
331996  -\n\nياغايب ٍ ماقلت لي وين دنياك\nكيف أمنع الغ...
331997  @saddahalotaibi انا ماقلت من اشعاري قلت بقلمي ...
331998  @Abushoug_ ياحسين انا ماقلت من اشعاري قلت بقلم...
331999  @6r8i1 @saddahalotaibi صح الابيات للشاعر سداح ...

                                                     text
332995  ياهل عمره ١٠ سنوات ماسك اعلام دول الخليج شعرفه...
332996  هههههههه #مطبوخه يبا مطبوخه 😂 https://t.co/vXc...
332997  يعني نسوي نفسهم احنا انظف وصورونا @IbrahimDash...
332998  @messi_10_com @Retired_q8 كبتن بدر المطوع بيعت...
332999  جم بالمية تقيمون سنه ٢٠١٧ ؟ \nانا عن نفسي ٩٠٪؜...

                                                     text
333995  @bashar__jassem \nبعدك انطفى العالم وما بقى في...
333996         @bashar__jassem \nاي كا تعرف ليش ما تسوي 😜
333997  نوال مزاااااااااج احسن مو بس مودي يتغير جنه شك...
333998  اللي يترحمون على صدام ويقولون انه كان بطل العر...
333999                @buabdulla221 \nيخسي اترحم على صدام

                                                     text
334995                           @Reoom يمقن اي يمقن لا 😍
334996  يلي تقول ان البحر فيه راحه \nجيته وزود صوت موج...
334997  ماعاد للضيقه بصدري مساحه \nمن كثر ضاقت  لاحاسي...
334998  بكتب شطر وابيكم تكملونه  .!\n\nتدرين لاغبتي وش...
334999  @DLOo3a88 \n\nصدقش 😉\n\nيازين وشهوله علينا تغل...

                                                     text
335995  @shuwaired @PerfectAcademy5 الله يرضى عليك يا ...
335996    @tayseerrashedan أحسنت .. ونعم الأخلاق والتربية
335997                     @bosaif56 6  بس چني4  مع حفيدي
335998         @bosaif56 اللهم آمين أجمعين \nولد العم 🤲🏻🌹
335999  @bosaif56 هم أكثر الناس عنصرية فعلاً \nأما قول...

                                                     text
336995        @buazizan هذا شي زين تصير البورصه صبح و ليل
336996  🇰🇼الله يطول في عمرك يابوناصر 🇰🇼 https://t.co/U...
336997  @aah1984 @MarRabeh حط بالك علي صاحبي 🌹 اذا يبي...
336998  @osamarashed2014 @ahmad_khatib مصر و الكويت بل...
336999  رتويت بلاش \n\nاذا ممكن 🌹🌹🌹🌹🌹🌹 https://t.co/q6...

                                                     text
337995  @saqrelm فيه ناس تخصص محاربةالشرفاء\nيعني مابع...
337996  @kthbda_omar الله يهداك يابوخالد\nتشبه أردوغان...
337997  @nawafalhamly ونعم فيهم والله يرحم أبوسعد\nومش...
337998  @Khaledathoughts دايم نسمع هالجمله من 1992\n(د...
337999  @amjaadmmmmm يونس شلبي\nهو الممثل الوحيد اللي ...

                                                     text
338995  @s_spoot مبين انه حوش ، بس حسبت عليه عريش أو س...
338996  @omjasem23 هههههههه عرفتي الحين سبب تدهور القا...
338997           @bojassem73 هلا أخوي بو جاسم🌹مساء البركة
338998  @6wee6er هههههههه حرب الرموز 😄\nهذي حاله عاد !...
338999  @6wee6er هلا طال عمرك🌹مساء الرضا https://t.co/...

                                                     text
339995  حتى الكمبيوتر حايشته حالة إغماء مو راضي يشتغل 😩😩😩
339996             احنا اللي ما ينرد لنا طلب اذا بغيناه🌹🙏
339997  اللي يقولون قيمات كلش مو زين يقرون تحلطم اليوم...
339998     @zamillesdair عاد اشدعوه عليج شي عظيم ماله وصف
339999  @rababbaddah ياااابختى بهالشهاده حاااااضر من ع...

                                                     text
340995  @Amiraaa11kuwait أبتلشنا مع هالنوم الكل يعاني ...
340996                    @me_q81 أنشهد إنك صدقت يامشعل 👍
340997      @q8y1980 @UBxhxbx2 @Fne6L ابو تتن وش يطلع هذا
340998                           @UBxhxbx2 هو وينه بو تتن
340999                     @UBxhxbx2 خليه يطلع راسه بوتتن

                                                     text
341995    محد يسرق شخص من شخص \nبس الرخيص الكل يجيب راسه.
341996                       ما شاء الله الهوىٰ إستشوار 😐
341997                         إلى متى هالأسئله مالها رد؟
341998  اييي والله بس لجيتونااااا😂 https://t.co/Oarj4N...
341999  ياعمري انتي والله فاقدينج ❤️😩 https://t.co/OP3...

                                                     text
342995  #قياده_المراه_السعوديه_للسياره.  تبون الصحيح ف...
342996  #البصمه بصمه او غير بصمه بدون نفعه التجار يبون...
342997  الشباب اللي يبون يتزوجون يتشرطون يبون الزوجه م...
342998  #مظاهرات_حايل معقوله علشان رشيديه اخذ شمريه عس...
342999  العرب سابقا متخلفين والحين مع الشيلات ويش نسمي...

                                                     text
343995                  @molaaaa78 ويكون ماكل آش چان تكمل
343996        @molaaaa78 اهم شي المشية يعني عادي مو متعور
343997  @AlsaifEmad استاذ عماد من صياغ الخبر واقحام اس...
343998  لحقت على اللي قبلها اللي تدور وتحتها مغناطيس h...
343999  @shishtari @A_majeed_Karam من خله روحة سبوس ال...

                                                     text
344995                       احلى سلام مربع لإدارة المرور
344996  حكومتي الموقره انه شفت باليوتيوب سياكل تطير لو...
344997  انسان حالي من حاله ولا يفرق عني شي لا بنسب ولا...
344998  يقول المثل المصري//\n\nاذا لقيت العبيط ومستعبط...
344999  @Mohammad454 \n\nبوعبدالله انه ما اعرف مسؤول س...

                                                     text
345995  @renezi04 مودريج ١٠٠%١٠٠ وين راح ديبروين\nوين ...
345996  @teto__88 تبي الحق ولا ولد عمه؟\nمافيها شي يحط...
345997    شكلي اذا سكرت تارقت 🤣🤣🤣 https://t.co/huDHIZQFOl
345998  @ahmad_alenizy روعه\nبس الجزء الاول راح تمل شو...
345999  https://t.co/ycLMhJzfGCلاتلعب بنار تحق اصابيعك...

                                                     text
346995  #الكويت_استراليا  ثامر عناد وفهد عوض شنو دورهم...
346996                 @abrari14 ساعه ؟ انا من بعد رمضان🌚
346997                   @electroniyah تبي لحم ولا دياي ؟
346998  @a7madHadi غير صحيح هذي أثر الرمية الملتهبة 🤽🏼‍♀️
346999               @moltov80_ حسبي الله عليه الله يروعه

                                                     text
347995  غرد بأذني ما ابي الناس تسمع وش تقول https://t....
347996                    بعد اذنكم \nناخذ فاصل و نواصل 😊
347997    العسل \n\nموجود \n\nباقي \n\nالسمن الطيب \nوينه
347998  احلااااا ايامي \n\nمعاج يا اغلا أاا \nمن عرفته...
347999                      ياعذابي \n\nكيف انا بقو غيابك

                                                     text
348995     @yousif887 وانت ان شاء الله اطيب جزاك الله خير
348996      @barc_69 الله يشافيه يارب ويلبسه لباس العافيه
348997  @ayadboasamh @FaisalHQ8 اللهم امين يارب \nجزاك...
348998  @adnan79r جزاك الله خير \nهذا اب لجميع من عرفه...
348999  @Nada77819707 واجرك يارب \nجزاج الله خير اختي ...

                                                     text
349995  كأنك حاط الجنين بخلاط مولينكس https://t.co/whk...
349996  @NbolHr @d3dour طبعا لازم وهذي ليلة بالعمر خل ...
349997  @Sami_Alhashan اليوم اكبر غبي اللي يرتكب جريمة...
349998               @Almajlliss غيروا منهج كفايات الفاشل
349999  وراس امي و ابوي قانون التقاعد المبكر ما راح يك...

                                                     text
350995  @AlshaerRasheed خل يشوفون رواتب الوافدين وخاصة...
350996  @lovkuwait4ever @JassemAlabdulh2 @AlshaerRashe...
350997  @abdallahh_10 واللي أكثر من جذي اذا الكرة طاحت...
350998  @azizBOMEJDAD المضحك شوف منو اللي مشى جدام بو ...
350999  @AryanKhalil @gevwey هالتصويت كان بالموافقة عل...

                                                     text
351995  يامدعي بالعشق والحب والشوق \nعطني دليلك بالغلا...
351996  يقول (  اسمي ) و أنا أقول لبيہ\nو يقول لبى من ...
351997  تبي تحب آلنآس\nلاتجرح آلنآس \nتبي تعيش بخير\nل...
351998  صمت الغلا في داخلي يكتب ابيات\nعيت قوافي الشعر...
351999  دام المساء يجمع على الود قلبين \nيسعد مساء نبض...

                                                     text
352995  حولهم محكمه وتسفير هم وعرجهم بس فصل والله تعبت...
352996  وزيره تخطأ بالأرقام شنو نترجي هزلت https://t.c...
352997  خوش وزرا ما تشوفون البلد حالها حااااال https:/...
352998  الحمدالله والشكر علي سلامه تاج راسنا ابونا بو ...
352999  الشؤون بالدرجه الاول المسؤوله هي الي تخصص للوا...

                                                     text
353995  @aladwani71 هذا حيوان \nلازم يحطونه بقفص وكل م...
353996  @E_8ZX @aladwani71 اولا هذا طفل ما يحتاج هذا ا...
353997      @bo_Fawaz82 شلون ابره بدل الغسيل \nممكن اسمها
353998       @balbarghash تطوع بند مكافئة\nوحلوة في ال CV
353999  @ALIALROUMI ما يطيح سوقهم \nبيخلونهم حق المصاف...

                                                     text
354995  الانتر يبون\nخاميس\nسانشيز\nدي باول\nفالكاوي\n...
354996  بكوريا مسوين افتتاح بطوله البيسبول\nالله يالاب...
354997  @eidan22 الي يحط حساب وهمي\nشنو يفكر فيه !!\n\...
354998  يصور نفسه وهو يوصخ جسر جابر الجديد وواحد يصور ...
354999  القادسيه فاز\nالكويت خسر\n\nفرق بينهم ٣ نقاط\n...

                                                     text
355995      @I_9mile اللي ماكل فول مو من مصلحته هالحركة 😅
355996  يا اللي علَى كِثْرْ السواليف مِعتادْ\nأنا على ...
355997                     @Haneen218 و ناس ريحتهم حلوة 😊
355998  أمَّا نعيمه .. نعمين .. خَلِّيْ عْليوهْ يْكَلَ...
355999  @Rewayati كاولية .. هذي أحد نتايج التجنيس العش...

                                                     text
356995  @nawaaf_1978 صارلنا اكثر من عشر سنين على نفس ا...
356996  @nawaaf_1978 الاستهبال وااايد ابرك من الاستعبا...
356997  @nawaaf_1978 ع العموم الايام بينا وراح اذكرك ....
356998  @nawaaf_1978 @S_Alajmi90 ههههههه يا عمي اهم حت...
356999  اذا الرياضة بكبرها واقفة عندنا .. مادري هذيل ع...

                                                     text
357995           @al_rukhaimi اي والله …ذبحونا بتناقضاتهم
357996  @PhD_Q8i أنا متأكد أن الشعب واعي.. و يعرف من ا...
357997  @alajlah929 @audiq55 @totalq8y24 @Bent_B_K يا ...
357998  @bu_dekho @O_Alkhashram افعالهم !؟ انهم بالسجن...
357999                 @Nina0kuwaiteya بالضبط … عبث و عبط

                                                     text
358995  @kakpol1 @brokerq8 @cma_kwt شنسوي تدبسنا بهالا...
358996         @Almajlliss هذيله مو مال يسوقون فيهم اعصاب
358997  @alsafir_1M يمكن خذتها ووافقت عليه لان يصلي بع...
358998                 @PlusKuwait شعنده خالد بن الوليد 😬
358999           @dr_a_altraiji اااامين تحفظنا يا رب منهم

                                                     text
359995  @khaledmm35 بعدي يالذيب اردى فعايلك 💪🏾 https:/...
359996  @a_alshatti \nتوله عليكم العافيه ، إن شاءالله ...
359997  @anwaralhabsi \nهههههههههه على ايدك نحتاج التر...
359998  طريق ابوحدريه وفطور على الطاير 😋 https://t.co/...
359999  @Hedo_1982 \nمعاهم حق الناس عندهم اجنده لسنوات...

                                                     text
360995  @S3AD_MFH فراغنا السرمدي المدمغ هو سبب تحلطمنا...
360996  @S3AD_MFH @jumankw لايكون من هذول طاقة سلبية و...
360997  @ZainaMAA الاخيرة لها مفعول سحري بحياتج اذا حذ...
360998  @Fawazoalameer3 \nكنت مسويتلك فولو مادري من شا...
360999   @saeedtawfiqi @TishallaaFaisal مو واضح كلش الرقم

                                                     text
361995  اكو. مثل عربي. قال خيل الخيل عام الاول. قال له...
361996  هم خوال كرباج راحو السعوديه. ؟ انا خابرهم ورا ...
361997  هذا شنو. ومنين طلع لنا هو ونخاريره بعد. ناقصيي...
361998  @al_aneeq3 اشوووف الزبيدي. رخيص يمكن لو ينحدق....
361999  اعزمني مره ع الحداق معاك. بس ترى ماعرف اعوووم ...

                                                     text
362995  ودعتـك الله ؛ وآلوعد صـدفة لقـى\nتلمحك عيني وآ...
362996  وتتسائل وش اكثر جرح ما ينزف \nترا آخر جروحك جت...
362997  يوم شفت البعد خيره .. خفت من بعدك وشره \nواستخ...
362998  يومها بين يديني والغلآ عادي\nيوم قفت تفجر حبها...
362999  تخليني وانا لي معك تغريبه وملح وعيش\nتخليني وا...

                                                     text
363995  وقبر 🙂 من زين حياتك عشان يدخلون فيها اصلاً حما...
363996  في فاشنيستا سعوديه عايشه برا حياتها كلها سوالف...
363997   @AshwaqAlAli75 😂😂😂😂ماما ما اتحمل فيني حب التملك😂
363998  امي قاسيه 😂💔 يارب زوج المستقبل مايشوف هالتويت ...
363999  @AshwaqAlAli75 ابي حليو وباله طويل و دمه خفيف ...

                                                     text
364995  @Alsayegh10 غير صحيح كل أهل الخليج مدلعين و مس...
364996  @jinwoz @Hamadalowaisi @al5aga95 هذا بالضبط أل...
364997  الشرع عدل بين كل الناس اللي تحت حكمك\n.\nما في...
364998  @alqabas سلمان الحمود وقع في شباك نواب جدد متح...
364999  @7bary_kw @AlsuwaidanHasan في هيئات وايد شغاله...

                                                     text
365995  هلا بالحبيب.\n\nاللي غابت طلته المسائية إلا من...
365996  كفو عالشقردية عيال الكويت https://t.co/B74X8cTCwg
365997  هذا كاريكاتير قديم جدا. الوضع الحالي قابل لرسم...
365998  المجد صنعة عز و توفيق تبي عزوم. ما يجي بخسة ثع...
365999  يا مبارك العز ربيعنا ماصحو من لذة النوم. الأصا...

                                                     text
366995  @Danaalshattii محد بس صايره دراما وأحب أعيش دو...
366996  @Msalsaffar الحين أنا المفروض أهديچ هالأغنيه😂😂😂😂😂
366997  @tamerhosny احلى سبايدر مان في الدنيا كلهاااا❤...
366998  @danaalsaglawi @tamerhosny هووو اييي عادي شفيك...
366999  @AishaAlhaqqan @barazi__ اي والله اقروا على نف...

                                                     text
367995  يِشهد الله إنّي أحبّك ، لِين ضآقَت ضُلوعِي وَ ...
367996  لولآ آلخطآ محدن تعلم من آلنآس ولولآ آلجفآ محدن...
367997  #غرد_كأنك_في_2050\n\nملعب أستاد جابر صار سكن ع...
367998  @MAboja3fr كفو يا بوجعفر يا ريت كل شباب البدون...
367999                      @MAboja3fr أجمعين إن شاء الله

                                                     text
368995  @alsafir_1M ياحظهم عندهم خباز حنا بالاحمدي ماع...
368996  @Kuwait_Tweets @nasir_alarbash لاتوهق العالم ت...
368997  @sabahalkhozai @elyaso279 المثل يقول\nضعيف وطق...
368998  @TurkiBarrak @kooom911 تركي انت ماتفكر؟من وين ...
368999  @MAldhawy @kuwMowaten @n1970lion @Ghareb_fe_w6...

                                                     text
369995  #قلبك_لمن_يشتاق\n\nلما أشوفك محتفظ فيني ومتمسك...
369996   ودي اطلع اتمشى بس خاف من قوة الهوى تطير سيارتي 😥
369997               @jeekr69 والله حظكم قايم ماشاءالله 🤗
369998  تذكرونه ؟؟\n\nراح زمانه وانا ماعرف ادخله بالمس...
369999  @Elobd158 انا المسجل العادي ماعرف له هالمره سي...

                                                     text
370995  @grayarea_kw ياربي ياحبيبي الطف بعيالي بعد عين...
370996  @1llc__ رأي الشيخ مازن مو ملزم حق احد\nثانيا ج...
370997  @safaalhashem شنو فايده حضورج للجلسات لما تسحب...
370998  @naserr900 @xXProudSwordXx @NourBGZ ((سوء)) اخ...
370999  الصورة تبين مباشرة الاعمال في مشروع #من_باع_بي...

                                                     text
371995  @Ahmad_Alenezi62 @QadsiaClub يعتمد على الحاله ...
371996       شباب اي آيه وصلتوا؟؟ https://t.co/xhMNuNG1v6
371997              @Qadsia_News ليش لابسين أخضر عاد؟؟!!!
371998  مجلس الأمه يخدع الأمه من خلال اعضائه في قضية ز...
371999             @3NewsQ8 حسبي الله عليه تراه ماسوا خير

                                                     text
372995  @n_alnasserr لالا البنت اثبتت اقوى مقارنتآ مع ...
372996             @balathob883 طب وش ابغاله انا اسعد 😒😂😂
372997  واحد شاف بنت نحيفة قالها : \nهااي .. ايش تشتغل...
372998  هل تعلم 😊\n\nلو البنات يحطون صورهم الحقيقيه عر...
372999  😁😁 واحد يقول خالي ارسل لي صوره\nوكان النت ضعيف...

                                                     text
373995                       @_xrima سلامات عسى ما شر 😅🚶🏻
373996   @_xrima اعطاك الله خيره وكفاك شره يتربي فعزك 😁✋🏻
373997              @_xrima اتكبري واتنسي ان شاء الله 😁✋🏻
373998  @Almozn24476 نسميه سيويا وبالعافيه عليكم احلى ...
373999  @Zo_o39 ما ادرس بو كماش فيهم زغفات الله لا قال...

                                                     text
374995               @ywTeytX6jykq4Ej \nيعين الجميع يا رب
374996  يا أجمل عيون ملاها الحب دمعات وشغب\nكل شوقٍ مر...
374997  إذا حد يحب التحشيش .. أنصحكم تتابعوا هالحساب ا...
374998  يعرفوك وتعرفهم\nيتابعوك وتتابعهم\nلا يتفاعلوا ...
374999  @CostlySoul93 @lights_93\nعندها ١٠ د ، وبعدها ...

                                                     text
375995  @_taac97 أنتِ بعد اعترفي طايرة من السعادة بعد ...
375996  وقولوا اسم الله على غزالٍ طبّ قولوا اسم الله !...
375997  أمس حلمت إن نزل مطر ف عمان، ولما شفت سناب طلع ...
375998  @Az_Hxx61 مباااااارك لش عزة 😍💃🏻 الله يعطيش خير...
375999       @Mohadfarai الله يبارك فيك محمد، إن شاء الله

                                                     text
376995  @_nasserk إن شاء بنهديكم الكأس من نآخذ هذي الب...
376996     @_nasserk تسلم مب غريب عليكم دام حاكمكم الصباح
376997  @MalakKuwait94 لا والله كفؤووو عليهم والله لو ...
376998  أهم شيء نتكلم عن عمان والكويت مالنا شغل بالهشت...
376999  أتمنى أشوف لي يرسلون مقاطع خليعه في هالهشتاق أ...

                                                     text
377995        انا اقول: شتب يور ماوس معاليك 😂😂\n\n#جت_ريل
377996  .\nأوبرا باريس، الموجودة في قصر غارنيي، واحدة ...
377997  @AlabriSaud @Sultan92busaidi @highness_sami با...
377998  .\nقبل فترة ما كنت مقتنع أبدا بالسناب شات، كنت...
377999  @n_alkhanbashi25 والله فضيحة كذا.. يعني تو بال...

                                                     text
378995                   @UmReem_93 غبيه وعقل ما فيها 😂😂😂
378996  @i_2iL هذا يسمونه الغباء بعينه، لأن كل ما قدمت...
378997           هالفترة حتى علاقتي بنفسي أحسها بتنتهي..💔
378998  احصل مجاناًعلى ايفون اكس اس \nhttps://t.co/u85...
378999  @SBQ_2 والله ٥٠ بيسه ما ادفع هذا بو قاصر ندفع ...

                                                     text
379995  جيتك وانا من  كثر  الشوق  محتاج \nاحتاج.  اكون...
379996  ماني من اللي ينحني بالسهوله ..\nلي هامة يخضع ل...
379997  سامح وغض الطرف لو كان ما كان..\nعمر البحر ماضا...
379998  ارسل قصايد شوق كله عشانك\nواختار اجمل شعر .بال...
379999  يا زين عقلي في هـوئ حبك سقط\nوصار حبك نبـــــض...

                                                     text
380995  @benabdoon5181 وين المشكلة؟ يمكن هم ما بادروا ...
380996  @FaisalAlRuhaili 😳انا بس كتبت رسبت \nمن وين طل...
380997  @FaisalAlRuhaili 😾 ما فهالامور\n👹👺😾الحين غضبان...
380998              @Omani_Crazy ف امريكا يسوو ترايات بعد
380999  انهضوا ي نكبة المستقبل\nالعصافير لها ساعه تناب...

                                                     text
381995  ايه أصير أحسن، ولا يمنعني شي\n ما دامه راسي حي...
381996  ايه أصير أحسن، بما إني نويت  \nوعزمت وخطيت \nب...
381997  اليوم ثاني أيام عيد ميلادي  ..\n\nيعني بسوي مش...
381998  @mayamn_ يلا مناك، انا ياي اطلب منج ، انتي تطل...
381999  اعرف وايد والله، طيبين يحلليلني و نمشي ع النية...

                                                     text
382995  اسعد ربي صباحكم بكل الخير والمحبه http://t.co/...
382996  @morningyouth عاشوا هل السبوق صوغه وشهبار بارك...
382997  @jsyabi @Wzar_Fanilh طيب سويلي انا شعار ببلاش ...
382998  شعور لا يوصف لما تخلص بحث التخرج🌚🎓✌🏻️\n#جسق ht...
382999  واحنا اللي ماسكين خطوط!! شكلك جالس في بيتك في ...

                                                     text
383995  @mediaaom @mralsiyabi تأكدي بعدك من العرض ما م...
383996  @bandersuleimani @jihad_jabr @alhussain_ali ما...
383997             @hafsawbs @AbuHamza45 هذا بو متوفر ههه
383998                    @abualkomboz شكرا لك مفيده جداً
383999  @omanisonly أنا أقولك ما حد يستاهل تضحي من أجل...

                                                     text
384995  @55hashimi للأسف خيي توي أشوف تغريدتك كنت عطيت...
384996    @omani_twitt اش من براءه الا قول مشروع نذاله😄😄😄
384997    @the_empreeess شفتي كيف\nينعاد علينا من أول 😄😄😄
384998  @the_empreeess هذي طاقة الجذب\nكل شوي نقول نبي...
384999  @55hashimi @the_empreeess اوه سلامات الحبيب عل...

                                                     text
385995  @_d7iiiM تغيرنا حب 😊😂\nمثل الصاحب كل فصل يجي و...
385996  @kholoodalyasi @OoredooOman @S_Alwahibi_92 \nي...
385997  @hayan_lamki أبشرك زائدين 😂\nبس انا واقفلهم با...
385998  @_Alkazrooni @iTMREN @alre22am @AlwaleedDos @k...
385999              @AlHusain22 شكلك عجب بيتوقف الخريف 🏃🏻

                                                     text
386995  كروسان ولأ كرواسون ما تفرق بيننا\nاللي ممكن يف...
386996  من اجمل الاختبارات العلمية والعملية اللي اجرين...
386997  #حقيقة_التدخين انه يخلي الناس تشوفك تدخن\nوصبا...
386998  @morningyouth  صباح الاجازه وطلعة للشارقه مع و...
386999  @al_wisal صلحوا ارسالكم ف الرستاق  ما قدرنا نك...

                                                     text
387995  @falkindi404 اهم شي يادكتور كل ما كان هالامور ...
387996  @StateAudit_Oman نبا شي ملموس وواقع يقنع الشعب...
387997  @omanijobscom اغلب الايميلات م فيها رد وكذلك ا...
387998  @Halafmradio وليش م اتقبل دام انها جات بطريقة ...
387999  @MuktarOman مثل هالامور المفروض الحكم م هين له...

                                                     text
388995  @Alwahibi7161 @7n_nada ابوي أشوفها الشر بعينها...
388996  @96MAS_ @yousif_alail وعمان بعد نصهم يحتفلون ن...
388997  @W2qkWn0jIauNzQY اقول قبل خلها تشيل الميكب بعد...
388998  @omani78342 😍😍😍يم يم يم لذيد وصحي مب احسن من ا...
388999  @squmm @omani78342 الحمدلله على نعمه ..وخفو عل...

                                                     text
389995  @alain_soul1 @alainfcae بعد كم سنة راح يعيروه ...
389996             @5aldinho ما سمعوه الشياب هههههههههههه
389997            @farisf9 والصورة عشان زيادة الرتويت !!!
389998  @Sl6___ @T7RY2T @alain_soul1 صراحه كان المفروض...
389999  @5aldinho @bujsem الحل يكون شيوتاني بدل خالد و...

                                                     text
390995    @Tbebo_sh يكفيني حش امس م ابا افطرك  اكثر 😂😂😂😂😂
390996  @r_squrose @vm88oo بعده عندي بصيص من الامل انه...
390997  @r_squrose @vm88oo مالت ع حظي 🌚  م تشكِ ابوي م...
390998          @izx01 @r_squrose هذي وحده 😂😂 شغالتكم انا
390999  @izx01 @r_squrose لالا خلاص شغلنا د.زاك عنده 😂...

                                                     text
391995  يلا الا أعز الناس \nحبايبك نحن\nزدنا قليل حنان...
391996  عيون الصيد نعسات عيونى\nوبالاهات النوم جافوني\...
391997  سلام الغالين\nمتابعي الأعزاء\nالموجودين الحين\...
391998  نيتي يا حلوين تبادل الريتوت\nمع الكل حبا وسواق...
391999  جيناكم يا حبايبنا\nلنقول مساء الخير\nواشوفكم ك...

                                                     text
392995  #موكب30يونيو\n\nوبرضو حقتنا\nسلمنا\nسلم مفاتيح...
392996  @SDN_BARQ جنجويد رباطه.  بلاويكم مصوره فيديو و...
392997  @Joy23830934 @McLad84 @HamoodAbutalib اقول خلي...
392998  ومافي دولة عربية تنتج الصمغ \nعلى كوكب الأرض ٣...
392999  هو والله مفروض امشي برااااهو بعد العمايل والمغ...

                                                     text
393995  @Potatush بفتش لي فيديو ولا حاجه تثبت ليك عروب...
393996  @looshi_alaa هسي موقفنا يكون شنو من الناس ديل ...
393997  والله ترا كلنا نحن السعوديه ربعنا واخوانا الري...
393998  لما زول يرسل لي مسج ويمسحها .. 😂 https://t.co/...
393999    الشارع بس ✌ 😌 \n#الرحيل_ياسيسي_او_النزول_للشارع

                                                     text
394995  @AbubakerMoh1 @Sudanese_Spt مويكب ما تامي لكن ...
394996  السودان عبارة عن زير لو داير تشرب موية لازم تب...
394997  في ايام السخانة الزول البعرف مكان الشمس \nويقع...
394998  آخر ما توصل إليه الصوفية من الكفر بالله الله م...
394999  اغرب ما سمعت من الصوفي الخنجر \nقال :يلم فيك و...

                                                     text
395995  @MonyAlbager @simookrpe السجاير كلو بتكون كملت...
395996  @aala_mehaisi @Abazarhassan وحاة الله البلد ده...
395997  @simookrpe 😁😁😁😁 والله شاي بموية صحه ده شاي خمس...
395998  @Tyrion_alsudani الراجل بتريق يا بنك بانثر ، ل...
395999          @simookrpe في ناس كتار حيعيشو فراغ رهيب 😁

                                                     text
396995  @salma_bakheet0 اعملي هسابك من النوئية دي ياهبيبة
396996           @AlaminEman احسن لينا من ميغان ننسي شوية
396997  @EdyCohen انت مرات بتضرب ضربة معلم ومرات تغريد...
396998  @EdyCohen مع انك اسرائيلي لكن مرات بتقول كلام درر
396999  @LolyAlSheikh سبحان الله ألاء الشيخ متوفرة قبل...

                                                     text
397995   البروفات خلصت\nجايين للكبيره .. \n#مليونية6ابريل
397996  @Husseno00o دا عيبنا بس والله ... ندس الكعب ون...
397997  @PureSoul_11 @MuramAbdAlwahab @Mohd3bdu   بعتق...
397998  @Alaaaaaa_xx بحث التخرج اللي عملته كان بيتكلم ...
397999  @Alaaaaaa_xx مع انو 88% منهم عمرهم فوق ال16 وم...

                                                     text
398995  @almodifer انت ليه تغريداتك كلها ممتازة جداً ك...
398996  @Sh3aib 😂😂😂والله السنغلا حلوة ،،، يعني اسي لو ...
398997  @Belmokhba 😍😍بغض النظر عن أي شي فريق بالمخبة ا...
398998    #عشان_تكون_مرتاح  الصلاة ثم الصلاة ثم الصلاة ❤️
398999  يا جماعة الناس تسمع كلام @BidzSaleh 😂😂 #ارجوكم...

                                                     text
399995  والله مانشستر دا انتهي الكورة شغالة يقلبو يجيب...
399996  امي وجلجغمية حجة كبيرة يشعرون بالزعل https://t...
399997  حصل معاي بالنص الجزء الاول دا بالذات https://t...
399998     لامن امشي مؤسسة حكومية https://t.co/rSmggLfx0l
399999  دكتورة كافلجين اذ زات يو 🤔؟ https://t.co/Ts2i7...

                                                     text
400995                         @LkY8b ههههه ايوا عديل كده
400996  @zolsudane @othman1622s @mshibly11 مافي صدمه و...
400997  @ummy3ms يعني قديم ننساو عموما اتقبض واسي في ا...
400998  @zolsudane @rana__7asan @mshibly11 ابوعمار ياخ...
400999  أمبارح حكينا قصه سودانيه وضربنا المثل الشعب ال...

                                                     text
401995                     @lolli2060 هههه ركبي واحد بدله
401996               @lolli2060 لازم تراجعي عشان مااللتهب
401997  @GamalEldinHamad @magdi_halim المشكله بقي اللخ...
401998  @husam_koko @magdi_halim من هناك بكون عارفين ح...
401999  @mqGH2rgIpGSrIci @magdi_halim ههههههه ماشي كوي...

                                                     text
402995  @khalidewais @IDalia_sef حسسسبي الله ونعم الوك...
402996  @moawi99 هههههههههه يولد ضرب الرصاص شغال وواحد...
402997  @coladabey2 @DinaAlmalik الله يحفظكم ويغطيكم ا...
402998  شباب عندي مويه كتيره وكمامات كتيره وكيك كتير ب...
402999               يديكم العافيه وماقصرتو لقينا سياره💓💓

                                                     text
403995          مين غبنك أكثر ديبالا وإلا رونالدو ؟.😹😹😹👋🏾
403996                   @ariam_store عاوز اطلب الشنطه دي
403997               @ReemooSalah مجخننه وين الله يكرمك 😳
403998  @AlharithMoh ١٠ وزراء زي مكاوي كفاية عشان السو...
403999  -الحوت م مات داسنو الامريكان مع توباك ومايكل ج...

                                                     text
404995  @M__albugaily 😂😂😂😂لا حول ولا قوة الا بالله الع...
404996  @modysa_78 @crazyhamoo @mtmnur20 طلع قريبك ولا...
404997  @Uranus909 @crazyhamoo @mtmnur20 ربنا يرحمها و...
404998  @AlqwasManal @egypt_stop @mogaber45 @MottalebN...
404999  @Uranus909 @crazyhamoo @mtmnur20 ايوة اول قالو...

                                                     text
405995           @sharjah1122 على ايامها كان قمة الكشخه 😀
405996                           @DR___ROSE بن روغه دي جي
405997  @ali_alhameri هذا اللي يقولك\nتشرّب العلم من ن...
405998  @SafaAlnaqbi @zayed_alkindy بس خمسينية في سن ا...
405999  @Mahabba_ و انا علي كل اسبوع اطرش لج كيسة برتق...

                                                     text
406995  @fxxxWKdSjdcXt0r تسلم يا اماراتي علـ الذوق ولا...
406996           @alhamadi_280 تسلم عيونك ما اباهن ابا🔥🦌🔥
406997        @9otae ماعليك زود ياسعيد الطيب والزين مرباك
406998                 @ALMSHTRI صباحك نور وسرور يابومييد
406999  @uae_love_ad121 الله الله شو هالكلام الحلو من ...

                                                     text
407995  @LuxuryNa9eR @etisalat راحت علي عيل لاني يوم ا...
407996        @SAADxZ20 كان هدية 💔, شكلك انت اللي بتعطيني
407997  الاضافة الجديدة في لعبة fortnite واللي تحول ال...
407998  @abk3bi اهم شي مافيها بقات pubg الغبية .. من 5...
407999  وبالمناسبة لعبة Fortnite راح تصبح مجانية السنة...

                                                     text
408995            انا اللي لساني طويل عاجزة عن التعبير 😭😭
408996   @bandar_a70 مبروووك يا زعيم وبالعافية البيتزا 😂💜
408997  تعرفون شو اكثر شي احترمه في هالانسان \n@Ghanim...
408998  انا ادري مابروم ارقد من الفرحة لكن لازم نرتاح ...
408999  صباحكم الزعيم اللي وصل لنهائي العالم بكل جدارة...

                                                     text
409995  @AltenaijiMusab @waseem_yousef وين بتروح من رب...
409996  ولا في عمرهم وحياتهم راح يناموا مرتاحين https:...
409997  @aalhosani_3 فدا حبي \nتعبانه لا اداومين باجر ...
409998  @Emarateyh @bent_zayed444 فدا حبيبتي انتي ❤😍\n...
409999  @bent_zayed444 @Emarateyh فديت قلبج حبيبتي \nل...

In [31]:
# saving to csv
df_text.to_csv('retreived_text_data.csv')